/*
 * A1 curriculum units. Authored content: metadata, teaching lessons, themed
 * vocabulary, and example sentences that use the unit's words + grammar. Most
 * exercises are generated from this by content/pipeline/exercises.ts; only
 * special drills are hand-authored via `exercises`.
 *
 * This file currently holds the first units as the pipeline is proven end-to-end;
 * the remaining A1 units are appended here.
 */

import type { UnitDef } from './types';

export const a1Units: UnitDef[] = [
  {
    level: 'A1',
    slug: 'a1-greetings',
    title_en: 'Greetings & Politeness',
    title_fr: 'Salutations et politesse',
    theme: 'greetings',
    grammar_focus: 'greetings, tu vs vous, basic politeness',
    description:
      'Say hello and goodbye, greet people at different times of day, and choose between the formal "vous" and the informal "tu".',
    lessons: [
      {
        type: 'grammar',
        title: 'Saying hello: tu vs vous',
        body_markdown: [
          '## Two ways to say "you"',
          '',
          'French has **two words for "you"**, and choosing correctly is a core politeness skill.',
          '',
          '- **tu** — informal. Use with friends, family, children, and people your own age you know.',
          '- **vous** — formal *and* plural. Use with strangers, older people, officials, and anyone you address as a group.',
          '',
          'When in doubt with an adult you don\'t know, **use `vous`**. It is never rude; `tu` can be.',
          '',
          '## Greetings by time of day',
          '',
          '- **Bonjour** — Hello / Good morning (any daytime).',
          '- **Bonsoir** — Good evening.',
          '- **Salut** — Hi / Bye (informal only).',
          '- **Bonne nuit** — Good night (going to bed).',
          '',
          '## Polite words',
          '',
          '`s\'il vous plaît` (please, formal), `merci` (thank you), `de rien` (you\'re welcome), `pardon` / `excusez-moi` (excuse me).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Greetings vocabulary',
        body_markdown: 'Core words for greeting people and being polite.',
      },
      {
        type: 'dialogue',
        title: 'At the bakery',
        body_markdown: [
          '**La cliente :** Bonjour, madame !',
          '**La boulangère :** Bonjour ! Vous désirez ?',
          '**La cliente :** Une baguette, s\'il vous plaît.',
          '**La boulangère :** Voilà. Autre chose ?',
          '**La cliente :** Non, merci. Au revoir !',
          '**La boulangère :** Au revoir, bonne journée !',
        ].join('\n\n'),
      },
    ],
    vocab: [
      { lemma_fr: 'bonjour', translation_en: 'hello / good morning', pos: 'interjection', ipa: 'bɔ̃ʒuʁ' },
      { lemma_fr: 'bonsoir', translation_en: 'good evening', pos: 'interjection', ipa: 'bɔ̃swaʁ' },
      { lemma_fr: 'salut', translation_en: 'hi / bye (informal)', pos: 'interjection', ipa: 'saly' },
      { lemma_fr: 'au revoir', translation_en: 'goodbye', pos: 'interjection', ipa: 'o ʁəvwaʁ' },
      { lemma_fr: 'merci', translation_en: 'thank you', pos: 'interjection', ipa: 'mɛʁsi' },
      { lemma_fr: 'de rien', translation_en: "you're welcome", pos: 'phrase', ipa: 'də ʁjɛ̃' },
      { lemma_fr: "s'il vous plaît", translation_en: 'please (formal)', pos: 'phrase', ipa: 'sil vu plɛ' },
      { lemma_fr: 'pardon', translation_en: 'sorry / excuse me', pos: 'interjection', ipa: 'paʁdɔ̃' },
      { lemma_fr: 'oui', translation_en: 'yes', pos: 'adverb', ipa: 'wi' },
      { lemma_fr: 'non', translation_en: 'no', pos: 'adverb', ipa: 'nɔ̃' },
      { lemma_fr: 'madame', translation_en: 'madam / Mrs', pos: 'noun', gender: 'f', ipa: 'madam' },
      { lemma_fr: 'monsieur', translation_en: 'sir / Mr', pos: 'noun', gender: 'm', ipa: 'məsjø' },
      { lemma_fr: 'bonne journée', translation_en: 'have a good day', pos: 'phrase', ipa: 'bɔn ʒuʁne' },
      { lemma_fr: 'à bientôt', translation_en: 'see you soon', pos: 'phrase', ipa: 'a bjɛ̃to' },
    ],
    sentences: [
      { text_fr: 'Bonjour, comment allez-vous ?', text_en: 'Hello, how are you?' },
      { text_fr: 'Salut, ça va ?', text_en: 'Hi, how are you?' },
      { text_fr: 'Merci beaucoup, madame.', text_en: 'Thank you very much, madam.' },
      { text_fr: 'Au revoir et bonne journée !', text_en: 'Goodbye and have a good day!' },
      { text_fr: 'Une baguette, s\'il vous plaît.', text_en: 'One baguette, please.' },
      { text_fr: 'Excusez-moi, monsieur.', text_en: 'Excuse me, sir.' },
      { text_fr: 'Non merci, à bientôt.', text_en: 'No thank you, see you soon.' },
      { text_fr: 'Bonsoir, bonne nuit !', text_en: 'Good evening, good night!' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-introductions',
    title_en: 'Introducing Yourself',
    title_fr: 'Se présenter',
    theme: 'introductions',
    grammar_focus: "je m'appelle / j'habite / je suis; subject pronouns",
    description:
      'Give your name, say where you live and where you are from, and ask others the same. Meet the verbs être and s\'appeler.',
    lessons: [
      {
        type: 'grammar',
        title: 'Talking about yourself',
        body_markdown: [
          '## The building blocks',
          '',
          'Three phrases carry most first conversations:',
          '',
          '- **Je m\'appelle…** — "My name is…" (literally "I call myself"). Ask: *Comment tu t\'appelles ?* / *Comment vous appelez-vous ?*',
          '- **J\'habite à…** — "I live in…" (a city). Use **en/au** for countries: *j\'habite en France*, *au Canada*.',
          '- **Je suis…** — "I am…" (from the verb **être**). *Je suis étudiant. Je suis français.*',
          '',
          '## Subject pronouns',
          '',
          '| French | English |',
          '| --- | --- |',
          '| je | I |',
          '| tu | you (informal) |',
          '| il / elle | he / she |',
          '| nous | we |',
          '| vous | you (formal/plural) |',
          '| ils / elles | they |',
          '',
          'Note: **je** becomes **j\'** before a vowel — *j\'habite*, *j\'aime*.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Introductions vocabulary',
        body_markdown: 'Words for names, origins, and simple personal details.',
      },
      {
        type: 'dialogue',
        title: 'Meeting someone new',
        body_markdown: [
          '**Léa :** Bonjour ! Comment tu t\'appelles ?',
          '**Marc :** Je m\'appelle Marc. Et toi ?',
          '**Léa :** Moi, c\'est Léa. Tu habites où ?',
          '**Marc :** J\'habite à Lyon. Je suis étudiant.',
          '**Léa :** Enchantée, Marc !',
          '**Marc :** Enchanté !',
        ].join('\n\n'),
      },
    ],
    vocab: [
      { lemma_fr: "je m'appelle", translation_en: 'my name is', pos: 'phrase', ipa: 'ʒə mapɛl' },
      { lemma_fr: 'habiter', translation_en: 'to live (somewhere)', pos: 'verb', ipa: 'abite' },
      { lemma_fr: 'être', translation_en: 'to be', pos: 'verb', ipa: 'ɛtʁ' },
      { lemma_fr: 'enchanté', translation_en: 'nice to meet you', pos: 'adjective', ipa: 'ɑ̃ʃɑ̃te' },
      { lemma_fr: 'un nom', translation_en: 'a name / surname', pos: 'noun', gender: 'm', ipa: 'nɔ̃' },
      { lemma_fr: 'un prénom', translation_en: 'a first name', pos: 'noun', gender: 'm', ipa: 'pʁenɔ̃' },
      { lemma_fr: 'un étudiant', translation_en: 'a student (m)', pos: 'noun', gender: 'm', ipa: 'etydjɑ̃' },
      { lemma_fr: 'une étudiante', translation_en: 'a student (f)', pos: 'noun', gender: 'f', ipa: 'etydjɑ̃t' },
      { lemma_fr: 'français', translation_en: 'French (m)', pos: 'adjective', gender: 'm', ipa: 'fʁɑ̃sɛ' },
      { lemma_fr: 'une ville', translation_en: 'a city / town', pos: 'noun', gender: 'f', ipa: 'vil' },
      { lemma_fr: 'un pays', translation_en: 'a country', pos: 'noun', gender: 'm', ipa: 'pei' },
      { lemma_fr: 'et toi', translation_en: 'and you? (informal)', pos: 'phrase', ipa: 'e twa' },
      { lemma_fr: 'où', translation_en: 'where', pos: 'adverb', ipa: 'u' },
      { lemma_fr: 'moi', translation_en: 'me', pos: 'pronoun', ipa: 'mwa' },
    ],
    sentences: [
      { text_fr: "Je m'appelle Marie.", text_en: 'My name is Marie.' },
      { text_fr: "J'habite à Paris.", text_en: 'I live in Paris.' },
      { text_fr: 'Je suis étudiant.', text_en: 'I am a student.' },
      { text_fr: 'Tu habites où ?', text_en: 'Where do you live?' },
      { text_fr: 'Je suis français.', text_en: 'I am French.' },
      { text_fr: 'Comment vous appelez-vous ?', text_en: 'What is your name?' },
      { text_fr: 'Enchanté, et toi ?', text_en: 'Nice to meet you, and you?' },
      { text_fr: 'Elle habite dans une grande ville.', text_en: 'She lives in a big city.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-numbers',
    title_en: 'Numbers 0–20',
    title_fr: 'Les nombres 0–20',
    theme: 'numbers',
    grammar_focus: 'cardinal numbers 0–20, il y a, asking quantities',
    description:
      'Count from zero to twenty, say how many there are with "il y a", and ask "how much?" with "combien".',
    lessons: [
      {
        type: 'grammar',
        title: 'Counting and quantities',
        body_markdown: [
          '## Numbers 0–20',
          '',
          '0 zéro · 1 un · 2 deux · 3 trois · 4 quatre · 5 cinq · 6 six · 7 sept · 8 huit · 9 neuf · 10 dix',
          '',
          '11 onze · 12 douze · 13 treize · 14 quatorze · 15 quinze · 16 seize · 17 dix-sept · 18 dix-huit · 19 dix-neuf · 20 vingt',
          '',
          '## il y a — "there is / there are"',
          '',
          '**il y a** works for both singular and plural: *il y a un chat* (there is a cat), *il y a trois livres* (there are three books).',
          '',
          '## Asking "how much / how many"',
          '',
          'Use **combien** — *C\'est combien ?* (How much is it?), *Combien de personnes ?* (How many people?).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Numbers vocabulary',
        body_markdown: 'The numbers zero to twenty, plus quantity words.',
      },
      {
        type: 'reading',
        title: 'At the market',
        body_markdown: [
          'Au marché, il y a beaucoup de fruits. J\'achète six pommes et quatre bananes.',
          '',
          'La vendeuse dit : « Ça fait dix euros. » Il y a aussi douze œufs pour trois euros. C\'est combien en tout ? Treize euros !',
        ].join('\n'),
      },
    ],
    vocab: [
      { lemma_fr: 'un', translation_en: 'one', pos: 'number', ipa: 'œ̃' },
      { lemma_fr: 'deux', translation_en: 'two', pos: 'number', ipa: 'dø' },
      { lemma_fr: 'trois', translation_en: 'three', pos: 'number', ipa: 'tʁwa' },
      { lemma_fr: 'quatre', translation_en: 'four', pos: 'number', ipa: 'katʁ' },
      { lemma_fr: 'cinq', translation_en: 'five', pos: 'number', ipa: 'sɛ̃k' },
      { lemma_fr: 'six', translation_en: 'six', pos: 'number', ipa: 'sis' },
      { lemma_fr: 'sept', translation_en: 'seven', pos: 'number', ipa: 'sɛt' },
      { lemma_fr: 'huit', translation_en: 'eight', pos: 'number', ipa: 'ɥit' },
      { lemma_fr: 'neuf', translation_en: 'nine', pos: 'number', ipa: 'nœf' },
      { lemma_fr: 'dix', translation_en: 'ten', pos: 'number', ipa: 'dis' },
      { lemma_fr: 'onze', translation_en: 'eleven', pos: 'number', ipa: 'ɔ̃z' },
      { lemma_fr: 'douze', translation_en: 'twelve', pos: 'number', ipa: 'duz' },
      { lemma_fr: 'vingt', translation_en: 'twenty', pos: 'number', ipa: 'vɛ̃' },
      { lemma_fr: 'combien', translation_en: 'how much / how many', pos: 'adverb', ipa: 'kɔ̃bjɛ̃' },
      { lemma_fr: 'il y a', translation_en: 'there is / there are', pos: 'phrase', ipa: 'il i a' },
    ],
    sentences: [
      { text_fr: "Il y a trois livres sur la table.", text_en: 'There are three books on the table.' },
      { text_fr: "J'achète six pommes.", text_en: 'I buy six apples.' },
      { text_fr: "C'est combien ?", text_en: 'How much is it?' },
      { text_fr: 'Il y a douze œufs.', text_en: 'There are twelve eggs.' },
      { text_fr: 'Nous sommes quatre.', text_en: 'There are four of us.' },
      { text_fr: 'Ça fait dix euros.', text_en: "That's ten euros." },
      { text_fr: 'Elle a deux chats.', text_en: 'She has two cats.' },
      { text_fr: 'Vingt personnes attendent dehors.', text_en: 'Twenty people are waiting outside.' },
    ],
  },
];
