/*
 * A1 curriculum units. Authored content: metadata, teaching lessons, themed
 * vocabulary, and example sentences that use the unit's words + grammar. Most
 * exercises are generated from this by content/pipeline/exercises.ts; only
 * special drills are hand-authored via `exercises`.
 *
 * This file currently holds the first units as the pipeline is proven end-to-end;
 * the remaining A1 units are appended here.
 */

import type { UnitDef } from './types';

export const a1Units: UnitDef[] = [
  {
    level: 'A1',
    slug: 'a1-greetings',
    title_en: 'Greetings & Politeness',
    title_fr: 'Salutations et politesse',
    theme: 'greetings',
    grammar_focus: 'greetings, tu vs vous, basic politeness',
    description:
      'Say hello and goodbye, greet people at different times of day, and choose between the formal "vous" and the informal "tu".',
    lessons: [
      {
        type: 'grammar',
        title: 'Saying hello: tu vs vous',
        body_markdown: [
          '## Two ways to say "you"',
          '',
          'French has **two words for "you"**, and choosing correctly is a core politeness skill.',
          '',
          '- **tu** — informal. Use with friends, family, children, and people your own age you know.',
          '- **vous** — formal *and* plural. Use with strangers, older people, officials, and anyone you address as a group.',
          '',
          'When in doubt with an adult you don\'t know, **use `vous`**. It is never rude; `tu` can be.',
          '',
          '## Greetings by time of day',
          '',
          '- **Bonjour** — Hello / Good morning (any daytime).',
          '- **Bonsoir** — Good evening.',
          '- **Salut** — Hi / Bye (informal only).',
          '- **Bonne nuit** — Good night (going to bed).',
          '',
          '## Polite words',
          '',
          '`s\'il vous plaît` (please, formal), `merci` (thank you), `de rien` (you\'re welcome), `pardon` / `excusez-moi` (excuse me).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Greetings vocabulary',
        body_markdown: 'Core words for greeting people and being polite.',
      },
      {
        type: 'dialogue',
        title: 'At the bakery',
        body_markdown: [
          '**La cliente :** Bonjour, madame !',
          '**La boulangère :** Bonjour ! Vous désirez ?',
          '**La cliente :** Une baguette, s\'il vous plaît.',
          '**La boulangère :** Voilà. Autre chose ?',
          '**La cliente :** Non, merci. Au revoir !',
          '**La boulangère :** Au revoir, bonne journée !',
        ].join('\n\n'),
      },
    ],
    vocab: [
      { lemma_fr: 'bonjour', translation_en: 'hello / good morning', pos: 'interjection', ipa: 'bɔ̃ʒuʁ' },
      { lemma_fr: 'bonsoir', translation_en: 'good evening', pos: 'interjection', ipa: 'bɔ̃swaʁ' },
      { lemma_fr: 'salut', translation_en: 'hi / bye (informal)', pos: 'interjection', ipa: 'saly' },
      { lemma_fr: 'au revoir', translation_en: 'goodbye', pos: 'interjection', ipa: 'o ʁəvwaʁ' },
      { lemma_fr: 'merci', translation_en: 'thank you', pos: 'interjection', ipa: 'mɛʁsi' },
      { lemma_fr: 'de rien', translation_en: "you're welcome", pos: 'phrase', ipa: 'də ʁjɛ̃' },
      { lemma_fr: "s'il vous plaît", translation_en: 'please (formal)', pos: 'phrase', ipa: 'sil vu plɛ' },
      { lemma_fr: 'pardon', translation_en: 'sorry / excuse me', pos: 'interjection', ipa: 'paʁdɔ̃' },
      { lemma_fr: 'oui', translation_en: 'yes', pos: 'adverb', ipa: 'wi' },
      { lemma_fr: 'non', translation_en: 'no', pos: 'adverb', ipa: 'nɔ̃' },
      { lemma_fr: 'madame', translation_en: 'madam / Mrs', pos: 'noun', gender: 'f', ipa: 'madam' },
      { lemma_fr: 'monsieur', translation_en: 'sir / Mr', pos: 'noun', gender: 'm', ipa: 'məsjø' },
      { lemma_fr: 'bonne journée', translation_en: 'have a good day', pos: 'phrase', ipa: 'bɔn ʒuʁne' },
      { lemma_fr: 'à bientôt', translation_en: 'see you soon', pos: 'phrase', ipa: 'a bjɛ̃to' },
    ],
    sentences: [
      { text_fr: 'Bonjour, comment allez-vous ?', text_en: 'Hello, how are you?' },
      { text_fr: 'Salut, ça va ?', text_en: 'Hi, how are you?' },
      { text_fr: 'Merci beaucoup, madame.', text_en: 'Thank you very much, madam.' },
      { text_fr: 'Au revoir et bonne journée !', text_en: 'Goodbye and have a good day!' },
      { text_fr: 'Une baguette, s\'il vous plaît.', text_en: 'One baguette, please.' },
      { text_fr: 'Excusez-moi, monsieur.', text_en: 'Excuse me, sir.' },
      { text_fr: 'Non merci, à bientôt.', text_en: 'No thank you, see you soon.' },
      { text_fr: 'Bonsoir, bonne nuit !', text_en: 'Good evening, good night!' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-introductions',
    title_en: 'Introducing Yourself',
    title_fr: 'Se présenter',
    theme: 'introductions',
    grammar_focus: "je m'appelle / j'habite / je suis; subject pronouns",
    description:
      'Give your name, say where you live and where you are from, and ask others the same. Meet the verbs être and s\'appeler.',
    lessons: [
      {
        type: 'grammar',
        title: 'Talking about yourself',
        body_markdown: [
          '## The building blocks',
          '',
          'Three phrases carry most first conversations:',
          '',
          '- **Je m\'appelle…** — "My name is…" (literally "I call myself"). Ask: *Comment tu t\'appelles ?* / *Comment vous appelez-vous ?*',
          '- **J\'habite à…** — "I live in…" (a city). Use **en/au** for countries: *j\'habite en France*, *au Canada*.',
          '- **Je suis…** — "I am…" (from the verb **être**). *Je suis étudiant. Je suis français.*',
          '',
          '## Subject pronouns',
          '',
          '| French | English |',
          '| --- | --- |',
          '| je | I |',
          '| tu | you (informal) |',
          '| il / elle | he / she |',
          '| nous | we |',
          '| vous | you (formal/plural) |',
          '| ils / elles | they |',
          '',
          'Note: **je** becomes **j\'** before a vowel — *j\'habite*, *j\'aime*.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Introductions vocabulary',
        body_markdown: 'Words for names, origins, and simple personal details.',
      },
      {
        type: 'dialogue',
        title: 'Meeting someone new',
        body_markdown: [
          '**Léa :** Bonjour ! Comment tu t\'appelles ?',
          '**Marc :** Je m\'appelle Marc. Et toi ?',
          '**Léa :** Moi, c\'est Léa. Tu habites où ?',
          '**Marc :** J\'habite à Lyon. Je suis étudiant.',
          '**Léa :** Enchantée, Marc !',
          '**Marc :** Enchanté !',
        ].join('\n\n'),
      },
    ],
    vocab: [
      { lemma_fr: "je m'appelle", translation_en: 'my name is', pos: 'phrase', ipa: 'ʒə mapɛl' },
      { lemma_fr: 'habiter', translation_en: 'to live (somewhere)', pos: 'verb', ipa: 'abite' },
      { lemma_fr: 'être', translation_en: 'to be', pos: 'verb', ipa: 'ɛtʁ' },
      { lemma_fr: 'enchanté', translation_en: 'nice to meet you', pos: 'adjective', ipa: 'ɑ̃ʃɑ̃te' },
      { lemma_fr: 'un nom', translation_en: 'a name / surname', pos: 'noun', gender: 'm', ipa: 'nɔ̃' },
      { lemma_fr: 'un prénom', translation_en: 'a first name', pos: 'noun', gender: 'm', ipa: 'pʁenɔ̃' },
      { lemma_fr: 'un étudiant', translation_en: 'a student (m)', pos: 'noun', gender: 'm', ipa: 'etydjɑ̃' },
      { lemma_fr: 'une étudiante', translation_en: 'a student (f)', pos: 'noun', gender: 'f', ipa: 'etydjɑ̃t' },
      { lemma_fr: 'français', translation_en: 'French (m)', pos: 'adjective', gender: 'm', ipa: 'fʁɑ̃sɛ' },
      { lemma_fr: 'une ville', translation_en: 'a city / town', pos: 'noun', gender: 'f', ipa: 'vil' },
      { lemma_fr: 'un pays', translation_en: 'a country', pos: 'noun', gender: 'm', ipa: 'pei' },
      { lemma_fr: 'et toi', translation_en: 'and you? (informal)', pos: 'phrase', ipa: 'e twa' },
      { lemma_fr: 'où', translation_en: 'where', pos: 'adverb', ipa: 'u' },
      { lemma_fr: 'moi', translation_en: 'me', pos: 'pronoun', ipa: 'mwa' },
    ],
    sentences: [
      { text_fr: "Je m'appelle Marie.", text_en: 'My name is Marie.' },
      { text_fr: "J'habite à Paris.", text_en: 'I live in Paris.' },
      { text_fr: 'Je suis étudiant.', text_en: 'I am a student.' },
      { text_fr: 'Tu habites où ?', text_en: 'Where do you live?' },
      { text_fr: 'Je suis français.', text_en: 'I am French.' },
      { text_fr: 'Comment vous appelez-vous ?', text_en: 'What is your name?' },
      { text_fr: 'Enchanté, et toi ?', text_en: 'Nice to meet you, and you?' },
      { text_fr: 'Elle habite dans une grande ville.', text_en: 'She lives in a big city.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-numbers',
    title_en: 'Numbers 0–20',
    title_fr: 'Les nombres 0–20',
    theme: 'numbers',
    grammar_focus: 'cardinal numbers 0–20, il y a, asking quantities',
    description:
      'Count from zero to twenty, say how many there are with "il y a", and ask "how much?" with "combien".',
    lessons: [
      {
        type: 'grammar',
        title: 'Counting and quantities',
        body_markdown: [
          '## Numbers 0–20',
          '',
          '0 zéro · 1 un · 2 deux · 3 trois · 4 quatre · 5 cinq · 6 six · 7 sept · 8 huit · 9 neuf · 10 dix',
          '',
          '11 onze · 12 douze · 13 treize · 14 quatorze · 15 quinze · 16 seize · 17 dix-sept · 18 dix-huit · 19 dix-neuf · 20 vingt',
          '',
          '## il y a — "there is / there are"',
          '',
          '**il y a** works for both singular and plural: *il y a un chat* (there is a cat), *il y a trois livres* (there are three books).',
          '',
          '## Asking "how much / how many"',
          '',
          'Use **combien** — *C\'est combien ?* (How much is it?), *Combien de personnes ?* (How many people?).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Numbers vocabulary',
        body_markdown: 'The numbers zero to twenty, plus quantity words.',
      },
      {
        type: 'reading',
        title: 'At the market',
        body_markdown: [
          'Au marché, il y a beaucoup de fruits. J\'achète six pommes et quatre bananes.',
          '',
          'La vendeuse dit : « Ça fait dix euros. » Il y a aussi douze œufs pour trois euros. C\'est combien en tout ? Treize euros !',
        ].join('\n'),
      },
    ],
    vocab: [
      { lemma_fr: 'un', translation_en: 'one', pos: 'number', ipa: 'œ̃' },
      { lemma_fr: 'deux', translation_en: 'two', pos: 'number', ipa: 'dø' },
      { lemma_fr: 'trois', translation_en: 'three', pos: 'number', ipa: 'tʁwa' },
      { lemma_fr: 'quatre', translation_en: 'four', pos: 'number', ipa: 'katʁ' },
      { lemma_fr: 'cinq', translation_en: 'five', pos: 'number', ipa: 'sɛ̃k' },
      { lemma_fr: 'six', translation_en: 'six', pos: 'number', ipa: 'sis' },
      { lemma_fr: 'sept', translation_en: 'seven', pos: 'number', ipa: 'sɛt' },
      { lemma_fr: 'huit', translation_en: 'eight', pos: 'number', ipa: 'ɥit' },
      { lemma_fr: 'neuf', translation_en: 'nine', pos: 'number', ipa: 'nœf' },
      { lemma_fr: 'dix', translation_en: 'ten', pos: 'number', ipa: 'dis' },
      { lemma_fr: 'onze', translation_en: 'eleven', pos: 'number', ipa: 'ɔ̃z' },
      { lemma_fr: 'douze', translation_en: 'twelve', pos: 'number', ipa: 'duz' },
      { lemma_fr: 'vingt', translation_en: 'twenty', pos: 'number', ipa: 'vɛ̃' },
      { lemma_fr: 'combien', translation_en: 'how much / how many', pos: 'adverb', ipa: 'kɔ̃bjɛ̃' },
      { lemma_fr: 'il y a', translation_en: 'there is / there are', pos: 'phrase', ipa: 'il i a' },
    ],
    sentences: [
      { text_fr: "Il y a trois livres sur la table.", text_en: 'There are three books on the table.' },
      { text_fr: "J'achète six pommes.", text_en: 'I buy six apples.' },
      { text_fr: "C'est combien ?", text_en: 'How much is it?' },
      { text_fr: 'Il y a douze œufs.', text_en: 'There are twelve eggs.' },
      { text_fr: 'Nous sommes quatre.', text_en: 'There are four of us.' },
      { text_fr: 'Ça fait dix euros.', text_en: "That's ten euros." },
      { text_fr: 'Elle a deux chats.', text_en: 'She has two cats.' },
      { text_fr: 'Vingt personnes attendent dehors.', text_en: 'Twenty people are waiting outside.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-articles',
    title_en: 'Gender & Articles',
    title_fr: 'Le genre et les articles',
    theme: 'grammar',
    grammar_focus: 'noun gender; definite le/la/les and indefinite un/une/des',
    description:
      'Every French noun is masculine or feminine. Learn the words for "the" (le, la, les) and "a" (un, une, des), and why you must learn each noun with its article.',
    lessons: [
      {
        type: 'grammar',
        title: 'Every noun has a gender',
        body_markdown: [
          '## Masculine or feminine',
          '',
          'Every French noun is either **masculine** or **feminine** — even objects. `le livre` (the book) is masculine; `la table` (the table) is feminine. There is no logic to it for objects, so **always learn a noun together with its article.**',
          '',
          '## "The" — the definite article',
          '',
          '- **le** — before a masculine noun: `le chat`, `le café`.',
          '- **la** — before a feminine noun: `la maison`, `la voiture`.',
          "- **l'** — before any noun starting with a vowel or silent h: `l'ami`, `l'eau`.",
          '- **les** — plural, for all genders: `les livres`, `les maisons`.',
          '',
          '## Endings can hint at gender',
          '',
          'Nouns ending in *-e* are often feminine (`la table`), and many others are masculine — but there are exceptions, so treat this as a hint, not a rule.',
        ].join('\n'),
      },
      {
        type: 'grammar',
        title: 'A, an, some',
        body_markdown: [
          '## The indefinite article',
          '',
          'Use these for "a / an / some" when the thing is not specific:',
          '',
          '- **un** — a (masculine): `un livre`, `un chien`.',
          '- **une** — a (feminine): `une pomme`, `une voiture`.',
          '- **des** — some (plural): `des amis`, `des pommes`.',
          '',
          'So `le livre` = **the** book (specific), but `un livre` = **a** book (any one).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Everyday nouns',
        body_markdown: 'Common nouns — memorize each one with its gender (le / la).',
      },
    ],
    vocab: [
      { lemma_fr: 'le livre', translation_en: 'the book', pos: 'noun', gender: 'm', ipa: 'lə livʁ' },
      { lemma_fr: 'la table', translation_en: 'the table', pos: 'noun', gender: 'f', ipa: 'la tabl' },
      { lemma_fr: 'la maison', translation_en: 'the house', pos: 'noun', gender: 'f', ipa: 'la mɛzɔ̃' },
      { lemma_fr: 'le chien', translation_en: 'the dog', pos: 'noun', gender: 'm', ipa: 'lə ʃjɛ̃' },
      { lemma_fr: 'le chat', translation_en: 'the cat', pos: 'noun', gender: 'm', ipa: 'lə ʃa' },
      { lemma_fr: 'la voiture', translation_en: 'the car', pos: 'noun', gender: 'f', ipa: 'la vwatyʁ' },
      { lemma_fr: "l'école", translation_en: 'the school', pos: 'noun', gender: 'f', ipa: 'lekɔl' },
      { lemma_fr: 'la porte', translation_en: 'the door', pos: 'noun', gender: 'f', ipa: 'la pɔʁt' },
      { lemma_fr: 'la fenêtre', translation_en: 'the window', pos: 'noun', gender: 'f', ipa: 'la fənɛtʁ' },
      { lemma_fr: "l'ami", translation_en: 'the friend (m)', pos: 'noun', gender: 'm', ipa: 'lami' },
      { lemma_fr: "l'amie", translation_en: 'the friend (f)', pos: 'noun', gender: 'f', ipa: 'lami' },
      { lemma_fr: "l'eau", translation_en: 'the water', pos: 'noun', gender: 'f', ipa: 'lo' },
      { lemma_fr: 'le stylo', translation_en: 'the pen', pos: 'noun', gender: 'm', ipa: 'lə stilo' },
      { lemma_fr: 'la ville', translation_en: 'the town / city', pos: 'noun', gender: 'f', ipa: 'la vil' },
    ],
    sentences: [
      { text_fr: 'Le chat est sur la table.', text_en: 'The cat is on the table.' },
      { text_fr: 'Je cherche un stylo.', text_en: 'I am looking for a pen.' },
      { text_fr: "L'école est fermée.", text_en: 'The school is closed.' },
      { text_fr: 'Une voiture attend devant la maison.', text_en: 'A car is waiting in front of the house.' },
      { text_fr: 'Les amis mangent des pommes.', text_en: 'The friends are eating some apples.' },
      { text_fr: "J'ai un chien et un chat.", text_en: 'I have a dog and a cat.' },
      { text_fr: 'La porte et la fenêtre sont ouvertes.', text_en: 'The door and the window are open.' },
      { text_fr: "L'eau est froide.", text_en: 'The water is cold.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-er-verbs',
    title_en: 'Present Tense: -er Verbs',
    title_fr: 'Le présent des verbes en -er',
    theme: 'grammar',
    grammar_focus: 'present tense of regular -er verbs; subject pronouns',
    description:
      'Most French verbs end in -er and follow one pattern. Learn to conjugate them in the present tense with je, tu, il/elle, nous, vous, ils/elles.',
    lessons: [
      {
        type: 'grammar',
        title: 'Conjugating regular -er verbs',
        body_markdown: [
          '## One pattern, hundreds of verbs',
          '',
          'About 90% of French verbs end in **-er** (like `parler`, to speak) and all follow the same present-tense pattern. Remove the `-er` to get the stem (`parl-`), then add the ending for each subject:',
          '',
          '- **je parle** — I speak',
          '- **tu parles** — you speak (informal)',
          '- **il / elle parle** — he / she speaks',
          '- **nous parlons** — we speak',
          '- **vous parlez** — you speak (formal / plural)',
          '- **ils / elles parlent** — they speak',
          '',
          'The endings are **-e, -es, -e, -ons, -ez, -ent**. Note that `-e`, `-es`, and `-ent` are all silent — `je parle`, `tu parles`, and `ils parlent` sound identical.',
          '',
          '## Try it with «habiter» (to live)',
          '',
          "`j'habite`, `tu habites`, `il habite`, `nous habitons`, `vous habitez`, `ils habitent`. (Before a vowel, `je` becomes `j'`.)",
        ].join('\n'),
      },
      {
        type: 'dialogue',
        title: 'Getting to know someone',
        body_markdown: [
          '**Léa :** Tu habites à Paris ?',
          '**Marc :** Non, j\'habite à Lyon. Et toi ?',
          '**Léa :** Moi, je travaille à Paris mais j\'habite à Versailles.',
          '**Marc :** Tu parles anglais ?',
          '**Léa :** Oui, et j\'étudie l\'espagnol aussi.',
        ].join('\n\n'),
      },
      {
        type: 'vocab',
        title: 'Common -er verbs',
        body_markdown: 'Useful regular -er verbs. They all conjugate like «parler».',
      },
    ],
    vocab: [
      { lemma_fr: 'parler', translation_en: 'to speak', pos: 'verb', ipa: 'paʁle' },
      { lemma_fr: 'habiter', translation_en: 'to live', pos: 'verb', ipa: 'abite' },
      { lemma_fr: 'aimer', translation_en: 'to like / to love', pos: 'verb', ipa: 'eme' },
      { lemma_fr: 'travailler', translation_en: 'to work', pos: 'verb', ipa: 'tʁavaje' },
      { lemma_fr: 'manger', translation_en: 'to eat', pos: 'verb', ipa: 'mɑ̃ʒe' },
      { lemma_fr: 'regarder', translation_en: 'to watch / to look at', pos: 'verb', ipa: 'ʁəɡaʁde' },
      { lemma_fr: 'écouter', translation_en: 'to listen (to)', pos: 'verb', ipa: 'ekute' },
      { lemma_fr: 'chercher', translation_en: 'to look for', pos: 'verb', ipa: 'ʃɛʁʃe' },
      { lemma_fr: 'jouer', translation_en: 'to play', pos: 'verb', ipa: 'ʒwe' },
      { lemma_fr: 'étudier', translation_en: 'to study', pos: 'verb', ipa: 'etydje' },
      { lemma_fr: 'chanter', translation_en: 'to sing', pos: 'verb', ipa: 'ʃɑ̃te' },
      { lemma_fr: 'danser', translation_en: 'to dance', pos: 'verb', ipa: 'dɑ̃se' },
      { lemma_fr: 'donner', translation_en: 'to give', pos: 'verb', ipa: 'dɔne' },
      { lemma_fr: 'trouver', translation_en: 'to find', pos: 'verb', ipa: 'tʁuve' },
    ],
    sentences: [
      { text_fr: 'Je parle un peu français.', text_en: 'I speak a little French.' },
      { text_fr: 'Nous habitons à Paris.', text_en: 'We live in Paris.' },
      { text_fr: 'Elle travaille dans un café.', text_en: 'She works in a café.' },
      { text_fr: 'Ils écoutent de la musique.', text_en: 'They are listening to music.' },
      { text_fr: 'Vous parlez très bien.', text_en: 'You speak very well.' },
      { text_fr: "J'aime le chocolat.", text_en: 'I like chocolate.' },
      { text_fr: 'Tu regardes la télévision ?', text_en: 'Are you watching television?' },
      { text_fr: 'Les enfants jouent dans le parc.', text_en: 'The children are playing in the park.' },
    ],
    exercises: [
      {
        type: 'cloze',
        prompt: 'Nous ____ français. (parler)',
        answer: 'parlons',
        accepted_alternatives: ['parlons'],
      },
      {
        type: 'cloze',
        prompt: 'Vous ____ à Lyon ? (habiter)',
        answer: 'habitez',
        accepted_alternatives: ['habitez'],
      },
      {
        type: 'cloze',
        prompt: 'Elle ____ dans un café. (travailler)',
        answer: 'travaille',
        accepted_alternatives: ['travaille'],
      },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-family',
    title_en: 'Family',
    title_fr: 'La famille',
    theme: 'family',
    grammar_focus: 'family vocabulary; possessive adjectives mon / ma / mes',
    description:
      'Talk about your family and say what belongs to whom with the possessive adjectives mon, ma, and mes.',
    lessons: [
      {
        type: 'grammar',
        title: 'My: mon, ma, mes',
        body_markdown: [
          '## "My" changes with the noun',
          '',
          'Unlike English, the word for **my** agrees with the noun that follows, not with the speaker:',
          '',
          '- **mon** — before a masculine noun: `mon père` (my father).',
          '- **ma** — before a feminine noun: `ma mère` (my mother).',
          '- **mes** — before any plural noun: `mes parents` (my parents).',
          '',
          '> **Tip:** before a feminine noun starting with a vowel, use **mon** for sound: `mon amie`.',
          '',
          'The same pattern gives **ton / ta / tes** (your) and **son / sa / ses** (his/her).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Family members',
        body_markdown: 'The core family words. Note the gender of each.',
      },
    ],
    vocab: [
      { lemma_fr: 'la famille', translation_en: 'the family', pos: 'noun', gender: 'f', ipa: 'la famij' },
      { lemma_fr: 'le père', translation_en: 'the father', pos: 'noun', gender: 'm', ipa: 'lə pɛʁ' },
      { lemma_fr: 'la mère', translation_en: 'the mother', pos: 'noun', gender: 'f', ipa: 'la mɛʁ' },
      { lemma_fr: 'le frère', translation_en: 'the brother', pos: 'noun', gender: 'm', ipa: 'lə fʁɛʁ' },
      { lemma_fr: 'la sœur', translation_en: 'the sister', pos: 'noun', gender: 'f', ipa: 'la sœʁ' },
      { lemma_fr: 'les parents', translation_en: 'the parents', pos: 'noun', gender: 'm', ipa: 'le paʁɑ̃' },
      { lemma_fr: 'le fils', translation_en: 'the son', pos: 'noun', gender: 'm', ipa: 'lə fis' },
      { lemma_fr: 'la fille', translation_en: 'the daughter / girl', pos: 'noun', gender: 'f', ipa: 'la fij' },
      { lemma_fr: 'le mari', translation_en: 'the husband', pos: 'noun', gender: 'm', ipa: 'lə maʁi' },
      { lemma_fr: 'la femme', translation_en: 'the wife / woman', pos: 'noun', gender: 'f', ipa: 'la fam' },
      { lemma_fr: "l'enfant", translation_en: 'the child', pos: 'noun', gender: 'm', ipa: 'lɑ̃fɑ̃' },
      { lemma_fr: 'le grand-père', translation_en: 'the grandfather', pos: 'noun', gender: 'm', ipa: 'lə ɡʁɑ̃pɛʁ' },
      { lemma_fr: 'la grand-mère', translation_en: 'the grandmother', pos: 'noun', gender: 'f', ipa: 'la ɡʁɑ̃mɛʁ' },
      { lemma_fr: 'la tante', translation_en: 'the aunt', pos: 'noun', gender: 'f', ipa: 'la tɑ̃t' },
      { lemma_fr: "l'oncle", translation_en: 'the uncle', pos: 'noun', gender: 'm', ipa: 'lɔ̃kl' },
    ],
    sentences: [
      { text_fr: "J'ai un frère et une sœur.", text_en: 'I have a brother and a sister.' },
      { text_fr: 'Mon père travaille beaucoup.', text_en: 'My father works a lot.' },
      { text_fr: 'Ma mère aime la musique.', text_en: 'My mother likes music.' },
      { text_fr: 'Mes parents habitent à Nice.', text_en: 'My parents live in Nice.' },
      { text_fr: 'Sa fille a cinq ans.', text_en: 'His/her daughter is five years old.' },
      { text_fr: 'Voici ma famille.', text_en: 'Here is my family.' },
      { text_fr: 'Le grand-père joue avec les enfants.', text_en: 'The grandfather plays with the children.' },
      { text_fr: 'Ton frère parle anglais ?', text_en: 'Does your brother speak English?' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-food',
    title_en: 'Food & Drink',
    title_fr: 'La nourriture et les boissons',
    theme: 'food',
    grammar_focus: 'ordering with «je voudrais»; the partitive du / de la / des',
    description:
      'Order food and drink politely and talk about eating "some" of something using the partitive articles du, de la, and des.',
    lessons: [
      {
        type: 'grammar',
        title: 'Some: the partitive article',
        body_markdown: [
          '## Talking about "some" food',
          '',
          'To say you eat or want **some** of something (an uncountable amount), French uses the **partitive article**:',
          '',
          '- **du** — some (masculine): `du pain` (some bread), `du café`.',
          '- **de la** — some (feminine): `de la salade`, `de la bière`.',
          "- **de l'** — before a vowel: `de l'eau`.",
          '- **des** — some (plural): `des fruits`, `des œufs`.',
          '',
          '## Ordering politely: «je voudrais»',
          '',
          '`je voudrais` means **I would like** — it is softer and more polite than `je veux` (I want). Use it to order:',
          '',
          "`Je voudrais un café, s'il vous plaît.` — I'd like a coffee, please.",
        ].join('\n'),
      },
      {
        type: 'dialogue',
        title: 'At the café',
        body_markdown: [
          '**Le serveur :** Bonjour, vous désirez ?',
          '**Le client :** Je voudrais un café et un croissant, s\'il vous plaît.',
          '**Le serveur :** Très bien. Et pour boire ?',
          '**Le client :** De l\'eau, merci.',
          '**Le serveur :** Voilà. Bon appétit !',
        ].join('\n\n'),
      },
      {
        type: 'vocab',
        title: 'Food and drink',
        body_markdown: 'Common items you can order or buy.',
      },
    ],
    vocab: [
      { lemma_fr: 'le pain', translation_en: 'the bread', pos: 'noun', gender: 'm', ipa: 'lə pɛ̃' },
      { lemma_fr: 'le fromage', translation_en: 'the cheese', pos: 'noun', gender: 'm', ipa: 'lə fʁɔmaʒ' },
      { lemma_fr: 'le café', translation_en: 'the coffee', pos: 'noun', gender: 'm', ipa: 'lə kafe' },
      { lemma_fr: 'le thé', translation_en: 'the tea', pos: 'noun', gender: 'm', ipa: 'lə te' },
      { lemma_fr: 'le vin', translation_en: 'the wine', pos: 'noun', gender: 'm', ipa: 'lə vɛ̃' },
      { lemma_fr: 'la pomme', translation_en: 'the apple', pos: 'noun', gender: 'f', ipa: 'la pɔm' },
      { lemma_fr: 'la salade', translation_en: 'the salad', pos: 'noun', gender: 'f', ipa: 'la salad' },
      { lemma_fr: 'le poulet', translation_en: 'the chicken', pos: 'noun', gender: 'm', ipa: 'lə pulɛ' },
      { lemma_fr: 'le poisson', translation_en: 'the fish', pos: 'noun', gender: 'm', ipa: 'lə pwasɔ̃' },
      { lemma_fr: 'le lait', translation_en: 'the milk', pos: 'noun', gender: 'm', ipa: 'lə lɛ' },
      { lemma_fr: 'un croissant', translation_en: 'a croissant', pos: 'noun', gender: 'm', ipa: 'œ̃ kʁwasɑ̃' },
      { lemma_fr: 'le sucre', translation_en: 'the sugar', pos: 'noun', gender: 'm', ipa: 'lə sykʁ' },
      { lemma_fr: 'le jus', translation_en: 'the juice', pos: 'noun', gender: 'm', ipa: 'lə ʒy' },
      { lemma_fr: 'je voudrais', translation_en: 'I would like', pos: 'phrase', ipa: 'ʒə vudʁɛ' },
    ],
    sentences: [
      { text_fr: 'Je voudrais un café, s\'il vous plaît.', text_en: "I'd like a coffee, please." },
      { text_fr: 'Il mange du pain et du fromage.', text_en: 'He is eating bread and cheese.' },
      { text_fr: 'Nous buvons du vin rouge.', text_en: 'We are drinking red wine.' },
      { text_fr: 'Elle voudrait de la salade.', text_en: 'She would like some salad.' },
      { text_fr: 'Le poulet est délicieux.', text_en: 'The chicken is delicious.' },
      { text_fr: "J'achète des pommes au marché.", text_en: 'I buy apples at the market.' },
      { text_fr: 'Un thé avec du sucre, merci.', text_en: 'A tea with sugar, thank you.' },
      { text_fr: 'Tu voudrais un croissant ?', text_en: 'Would you like a croissant?' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-days',
    title_en: 'Days, Months & Dates',
    title_fr: 'Les jours, les mois et les dates',
    theme: 'time',
    grammar_focus: 'days of the week, months, and saying the date',
    description:
      'Name the days and months, and say the date. Learn aujourd’hui, demain, and hier for talking about when things happen.',
    lessons: [
      {
        type: 'grammar',
        title: 'Days and months',
        body_markdown: [
          '## The days of the week',
          '',
          'French days are **not capitalized**: `lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche`. The week starts on Monday.',
          '',
          'Use **le** for something that happens every week: `le lundi` = on Mondays.',
          '',
          '## The months',
          '',
          '`janvier, février, mars, avril, mai, juin, juillet, août, septembre, octobre, novembre, décembre` — also lower-case.',
          '',
          '## Saying the date',
          '',
          'Pattern: **le + number + month**. `le 3 mars` (the 3rd of March). The only exception is the first: `le 1er mai` (le premier mai).',
          '',
          '`aujourd\'hui` = today, `demain` = tomorrow, `hier` = yesterday.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Time words',
        body_markdown: 'The days plus the words you need to place events in time.',
      },
    ],
    vocab: [
      { lemma_fr: 'lundi', translation_en: 'Monday', pos: 'noun', gender: 'm', ipa: 'lœ̃di' },
      { lemma_fr: 'mardi', translation_en: 'Tuesday', pos: 'noun', gender: 'm', ipa: 'maʁdi' },
      { lemma_fr: 'mercredi', translation_en: 'Wednesday', pos: 'noun', gender: 'm', ipa: 'mɛʁkʁədi' },
      { lemma_fr: 'jeudi', translation_en: 'Thursday', pos: 'noun', gender: 'm', ipa: 'ʒødi' },
      { lemma_fr: 'vendredi', translation_en: 'Friday', pos: 'noun', gender: 'm', ipa: 'vɑ̃dʁədi' },
      { lemma_fr: 'samedi', translation_en: 'Saturday', pos: 'noun', gender: 'm', ipa: 'samdi' },
      { lemma_fr: 'dimanche', translation_en: 'Sunday', pos: 'noun', gender: 'm', ipa: 'dimɑ̃ʃ' },
      { lemma_fr: "aujourd'hui", translation_en: 'today', pos: 'adverb', ipa: 'oʒuʁdɥi' },
      { lemma_fr: 'demain', translation_en: 'tomorrow', pos: 'adverb', ipa: 'dəmɛ̃' },
      { lemma_fr: 'hier', translation_en: 'yesterday', pos: 'adverb', ipa: 'jɛʁ' },
      { lemma_fr: 'la semaine', translation_en: 'the week', pos: 'noun', gender: 'f', ipa: 'la səmɛn' },
      { lemma_fr: 'le mois', translation_en: 'the month', pos: 'noun', gender: 'm', ipa: 'lə mwa' },
      { lemma_fr: 'le jour', translation_en: 'the day', pos: 'noun', gender: 'm', ipa: 'lə ʒuʁ' },
      { lemma_fr: "l'année", translation_en: 'the year', pos: 'noun', gender: 'f', ipa: 'lane' },
    ],
    sentences: [
      { text_fr: "Aujourd'hui, c'est lundi.", text_en: 'Today is Monday.' },
      { text_fr: 'Demain, je travaille.', text_en: 'Tomorrow I am working.' },
      { text_fr: 'Nous sommes le trois mars.', text_en: 'It is the third of March.' },
      { text_fr: 'Le samedi, je joue au football.', text_en: 'On Saturdays, I play football.' },
      { text_fr: 'Hier, il a plu.', text_en: 'Yesterday it rained.' },
      { text_fr: 'La semaine a sept jours.', text_en: 'The week has seven days.' },
      { text_fr: 'Mon anniversaire est en juin.', text_en: 'My birthday is in June.' },
      { text_fr: 'Le magasin est fermé le dimanche.', text_en: 'The shop is closed on Sundays.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-questions',
    title_en: 'Asking Questions',
    title_fr: 'Poser des questions',
    theme: 'grammar',
    grammar_focus: 'yes/no questions with est-ce que; question words',
    description:
      'Ask yes/no questions and use question words like où, quand, combien, and pourquoi to get the information you need.',
    lessons: [
      {
        type: 'grammar',
        title: 'Three ways to ask a yes/no question',
        body_markdown: [
          '## From statement to question',
          '',
          'Take `Tu parles français` (You speak French). You can turn it into a question three ways, from most casual to most formal:',
          '',
          '1. **Intonation** — same words, rising voice: `Tu parles français ?`',
          "2. **est-ce que** — add it to the front: `Est-ce que tu parles français ?`",
          '3. **Inversion** — swap verb and subject: `Parles-tu français ?` (formal).',
          '',
          'The `est-ce que` form is the most useful everyday option.',
          '',
          '## Question words',
          '',
          '- **qui** — who · **que / quoi** — what · **où** — where',
          '- **quand** — when · **comment** — how · **pourquoi** — why',
          '- **combien** — how much / how many',
          '',
          "Combine them with `est-ce que`: `Où est-ce que tu habites ?` (Where do you live?)",
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Question words',
        body_markdown: 'The words that start a question.',
      },
    ],
    vocab: [
      { lemma_fr: 'qui', translation_en: 'who', pos: 'pronoun', ipa: 'ki' },
      { lemma_fr: 'que', translation_en: 'what', pos: 'pronoun', ipa: 'kə' },
      { lemma_fr: 'où', translation_en: 'where', pos: 'adverb', ipa: 'u' },
      { lemma_fr: 'quand', translation_en: 'when', pos: 'adverb', ipa: 'kɑ̃' },
      { lemma_fr: 'comment', translation_en: 'how', pos: 'adverb', ipa: 'kɔmɑ̃' },
      { lemma_fr: 'combien', translation_en: 'how much / how many', pos: 'adverb', ipa: 'kɔ̃bjɛ̃' },
      { lemma_fr: 'pourquoi', translation_en: 'why', pos: 'adverb', ipa: 'puʁkwa' },
      { lemma_fr: 'parce que', translation_en: 'because', pos: 'conjunction', ipa: 'paʁs kə' },
      { lemma_fr: 'quel', translation_en: 'which / what (m)', pos: 'adjective', gender: 'm', ipa: 'kɛl' },
      { lemma_fr: 'quelle', translation_en: 'which / what (f)', pos: 'adjective', gender: 'f', ipa: 'kɛl' },
      { lemma_fr: 'peut-être', translation_en: 'maybe', pos: 'adverb', ipa: 'pøtɛtʁ' },
      { lemma_fr: 'bien sûr', translation_en: 'of course', pos: 'phrase', ipa: 'bjɛ̃ syʁ' },
    ],
    sentences: [
      { text_fr: 'Où est-ce que tu habites ?', text_en: 'Where do you live?' },
      { text_fr: 'Comment vous appelez-vous ?', text_en: 'What is your name?' },
      { text_fr: 'Pourquoi est-ce que tu apprends le français ?', text_en: 'Why are you learning French?' },
      { text_fr: "Combien ça coûte ?", text_en: 'How much does it cost?' },
      { text_fr: 'Quand est-ce que le train arrive ?', text_en: 'When does the train arrive?' },
      { text_fr: 'Quelle heure est-il ?', text_en: 'What time is it?' },
      { text_fr: 'Qui est cette femme ?', text_en: 'Who is that woman?' },
      { text_fr: 'Est-ce que tu aimes le café ?', text_en: 'Do you like coffee?' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-colours',
    title_en: 'Colours & Describing Things',
    title_fr: 'Les couleurs et les descriptions',
    theme: 'description',
    grammar_focus: 'adjective agreement and position',
    description:
      'Describe things with colours and common adjectives, and learn the two rules that trip up beginners: adjectives agree with the noun, and most go after it.',
    lessons: [
      {
        type: 'grammar',
        title: 'Adjectives agree and (usually) follow',
        body_markdown: [
          '## Agreement',
          '',
          'A French adjective changes to match the noun. The basic pattern: add **-e** for feminine, **-s** for plural.',
          '',
          '- `un pull vert` → `une robe verte` (feminine adds -e)',
          '- `un grand jardin` → `de grands jardins` (plural adds -s)',
          '',
          'Adjectives already ending in **-e** (like `rouge`, `jaune`) do not change in the feminine.',
          '',
          '## Position',
          '',
          'Most adjectives come **after** the noun: `une voiture rouge`, `un livre intéressant`.',
          '',
          'A small group of common ones come **before**: `bon, mauvais, grand, petit, beau, joli, nouveau, vieux`. → `un petit chien`, `une belle maison`.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Colours & adjectives',
        body_markdown: 'Colours and everyday describing words (masculine form shown).',
      },
    ],
    vocab: [
      { lemma_fr: 'rouge', translation_en: 'red', pos: 'adjective', ipa: 'ʁuʒ' },
      { lemma_fr: 'bleu', translation_en: 'blue', pos: 'adjective', ipa: 'blø' },
      { lemma_fr: 'vert', translation_en: 'green', pos: 'adjective', ipa: 'vɛʁ' },
      { lemma_fr: 'jaune', translation_en: 'yellow', pos: 'adjective', ipa: 'ʒon' },
      { lemma_fr: 'noir', translation_en: 'black', pos: 'adjective', ipa: 'nwaʁ' },
      { lemma_fr: 'blanc', translation_en: 'white', pos: 'adjective', ipa: 'blɑ̃' },
      { lemma_fr: 'grand', translation_en: 'big / tall', pos: 'adjective', ipa: 'ɡʁɑ̃' },
      { lemma_fr: 'petit', translation_en: 'small', pos: 'adjective', ipa: 'pəti' },
      { lemma_fr: 'beau', translation_en: 'beautiful / handsome', pos: 'adjective', ipa: 'bo' },
      { lemma_fr: 'joli', translation_en: 'pretty', pos: 'adjective', ipa: 'ʒɔli' },
      { lemma_fr: 'nouveau', translation_en: 'new', pos: 'adjective', ipa: 'nuvo' },
      { lemma_fr: 'vieux', translation_en: 'old', pos: 'adjective', ipa: 'vjø' },
      { lemma_fr: 'bon', translation_en: 'good', pos: 'adjective', ipa: 'bɔ̃' },
      { lemma_fr: 'mauvais', translation_en: 'bad', pos: 'adjective', ipa: 'movɛ' },
    ],
    sentences: [
      { text_fr: 'La voiture rouge est rapide.', text_en: 'The red car is fast.' },
      { text_fr: "C'est une belle maison.", text_en: 'It is a beautiful house.' },
      { text_fr: 'Il porte un pull vert.', text_en: 'He is wearing a green jumper.' },
      { text_fr: "J'ai un petit chien noir.", text_en: 'I have a small black dog.' },
      { text_fr: 'Les fleurs jaunes sont jolies.', text_en: 'The yellow flowers are pretty.' },
      { text_fr: "C'est un bon restaurant.", text_en: 'It is a good restaurant.' },
      { text_fr: 'Elle a une nouvelle robe bleue.', text_en: 'She has a new blue dress.' },
      { text_fr: 'Le vieux livre est intéressant.', text_en: 'The old book is interesting.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-house',
    title_en: 'The House & Rooms',
    title_fr: 'La maison',
    theme: 'home',
    grammar_focus: '«il y a»; prepositions of place (dans, sur, sous, devant)',
    description:
      'Describe your home and say where things are using «il y a» (there is/are) and prepositions of place.',
    lessons: [
      {
        type: 'grammar',
        title: 'There is / there are, and where',
        body_markdown: [
          '## «il y a» — there is / there are',
          '',
          'One phrase covers both singular and plural: `il y a une table` (there is a table), `il y a trois chaises` (there are three chairs). The negative is `il n\'y a pas de...`.',
          '',
          '## Prepositions of place',
          '',
          '- **dans** — in: `dans la cuisine`',
          '- **sur** — on: `sur la table`',
          '- **sous** — under: `sous le lit`',
          '- **devant** — in front of · **derrière** — behind',
          '- **à côté de** — next to: `à côté du salon`',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Rooms & furniture',
        body_markdown: 'The parts of a home and the things inside it.',
      },
    ],
    vocab: [
      { lemma_fr: "l'appartement", translation_en: 'the flat / apartment', pos: 'noun', gender: 'm', ipa: 'lapaʁtəmɑ̃' },
      { lemma_fr: 'la chambre', translation_en: 'the bedroom', pos: 'noun', gender: 'f', ipa: 'la ʃɑ̃bʁ' },
      { lemma_fr: 'la cuisine', translation_en: 'the kitchen', pos: 'noun', gender: 'f', ipa: 'la kɥizin' },
      { lemma_fr: 'la salle de bain', translation_en: 'the bathroom', pos: 'noun', gender: 'f', ipa: 'la sal də bɛ̃' },
      { lemma_fr: 'le salon', translation_en: 'the living room', pos: 'noun', gender: 'm', ipa: 'lə salɔ̃' },
      { lemma_fr: 'la chaise', translation_en: 'the chair', pos: 'noun', gender: 'f', ipa: 'la ʃɛz' },
      { lemma_fr: 'le lit', translation_en: 'the bed', pos: 'noun', gender: 'm', ipa: 'lə li' },
      { lemma_fr: 'le jardin', translation_en: 'the garden', pos: 'noun', gender: 'm', ipa: 'lə ʒaʁdɛ̃' },
      { lemma_fr: 'le mur', translation_en: 'the wall', pos: 'noun', gender: 'm', ipa: 'lə myʁ' },
      { lemma_fr: "l'escalier", translation_en: 'the stairs', pos: 'noun', gender: 'm', ipa: 'lɛskalje' },
      { lemma_fr: 'le canapé', translation_en: 'the sofa', pos: 'noun', gender: 'm', ipa: 'lə kanape' },
      { lemma_fr: 'la lampe', translation_en: 'the lamp', pos: 'noun', gender: 'f', ipa: 'la lɑ̃p' },
      { lemma_fr: 'la clé', translation_en: 'the key', pos: 'noun', gender: 'f', ipa: 'la kle' },
    ],
    sentences: [
      { text_fr: 'Il y a un canapé dans le salon.', text_en: 'There is a sofa in the living room.' },
      { text_fr: 'Le chat dort sous le lit.', text_en: 'The cat is sleeping under the bed.' },
      { text_fr: 'La lampe est sur la table.', text_en: 'The lamp is on the table.' },
      { text_fr: "Il y a trois chambres dans l'appartement.", text_en: 'There are three bedrooms in the flat.' },
      { text_fr: 'La cuisine est à côté du salon.', text_en: 'The kitchen is next to the living room.' },
      { text_fr: 'Les enfants jouent dans le jardin.', text_en: 'The children are playing in the garden.' },
      { text_fr: 'Où sont les clés ?', text_en: 'Where are the keys?' },
      { text_fr: "Il n'y a pas de fenêtre dans la salle de bain.", text_en: 'There is no window in the bathroom.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-time',
    title_en: 'Telling Time & Daily Routine',
    title_fr: "L'heure et la routine",
    theme: 'time',
    grammar_focus: 'telling the time; parts of the day',
    description:
      'Ask and tell the time, and talk about the parts of your day — morning, afternoon, evening.',
    lessons: [
      {
        type: 'grammar',
        title: 'What time is it?',
        body_markdown: [
          '## Asking and answering',
          '',
          'Ask: `Quelle heure est-il ?` Answer with **il est … heure(s)**:',
          '',
          '- `Il est une heure.` — It is one o\'clock.',
          '- `Il est trois heures.` — It is three o\'clock.',
          '',
          '## Minutes',
          '',
          '- **et quart** — quarter past: `deux heures et quart`',
          '- **et demie** — half past: `deux heures et demie`',
          '- **moins le quart** — quarter to: `trois heures moins le quart`',
          '',
          'Add **du matin** (a.m.), **de l\'après-midi** (afternoon), or **du soir** (evening) to be clear.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Time & the day',
        body_markdown: 'Words for clock time and the parts of a day.',
      },
    ],
    vocab: [
      { lemma_fr: "l'heure", translation_en: 'the hour / time', pos: 'noun', gender: 'f', ipa: 'lœʁ' },
      { lemma_fr: 'midi', translation_en: 'midday', pos: 'noun', gender: 'm', ipa: 'midi' },
      { lemma_fr: 'minuit', translation_en: 'midnight', pos: 'noun', gender: 'm', ipa: 'minɥi' },
      { lemma_fr: 'le matin', translation_en: 'the morning', pos: 'noun', gender: 'm', ipa: 'lə matɛ̃' },
      { lemma_fr: "l'après-midi", translation_en: 'the afternoon', pos: 'noun', gender: 'm', ipa: 'lapʁɛmidi' },
      { lemma_fr: 'le soir', translation_en: 'the evening', pos: 'noun', gender: 'm', ipa: 'lə swaʁ' },
      { lemma_fr: 'la nuit', translation_en: 'the night', pos: 'noun', gender: 'f', ipa: 'la nɥi' },
      { lemma_fr: 'tôt', translation_en: 'early', pos: 'adverb', ipa: 'to' },
      { lemma_fr: 'tard', translation_en: 'late', pos: 'adverb', ipa: 'taʁ' },
      { lemma_fr: 'maintenant', translation_en: 'now', pos: 'adverb', ipa: 'mɛ̃tənɑ̃' },
      { lemma_fr: 'le petit-déjeuner', translation_en: 'breakfast', pos: 'noun', gender: 'm', ipa: 'lə pəti deʒøne' },
      { lemma_fr: 'le déjeuner', translation_en: 'lunch', pos: 'noun', gender: 'm', ipa: 'lə deʒøne' },
      { lemma_fr: 'le dîner', translation_en: 'dinner', pos: 'noun', gender: 'm', ipa: 'lə dine' },
    ],
    sentences: [
      { text_fr: 'Quelle heure est-il ?', text_en: 'What time is it?' },
      { text_fr: 'Il est huit heures du matin.', text_en: 'It is eight in the morning.' },
      { text_fr: 'Je prends le petit-déjeuner à sept heures.', text_en: 'I have breakfast at seven.' },
      { text_fr: 'Le soir, nous regardons un film.', text_en: 'In the evening, we watch a film.' },
      { text_fr: 'Il est midi, on déjeune.', text_en: "It's midday, let's have lunch." },
      { text_fr: 'Tu travailles tard aujourd\'hui ?', text_en: 'Are you working late today?' },
      { text_fr: 'Le train part à trois heures et quart.', text_en: 'The train leaves at quarter past three.' },
      { text_fr: 'Maintenant, je suis fatigué.', text_en: 'Now I am tired.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-weather',
    title_en: 'Weather & Seasons',
    title_fr: 'Le temps et les saisons',
    theme: 'weather',
    grammar_focus: 'weather with «il fait» and «il y a»; the seasons',
    description:
      'Talk about the weather and the seasons — and learn why French uses "it makes" to describe how it feels outside.',
    lessons: [
      {
        type: 'grammar',
        title: 'Describing the weather',
        body_markdown: [
          '## «il fait» + adjective',
          '',
          'French describes weather with **il fait** (literally "it makes"):',
          '',
          '- `Il fait beau.` — The weather is nice.',
          '- `Il fait chaud / froid.` — It is hot / cold.',
          '',
          '## «il y a» and single verbs',
          '',
          '- `Il y a du soleil / du vent.` — It is sunny / windy.',
          '- `Il pleut.` — It is raining. · `Il neige.` — It is snowing.',
          '',
          '## The seasons',
          '',
          '`le printemps` (spring), `l\'été` (summer), `l\'automne` (autumn), `l\'hiver` (winter). Use **en** for three and **au** for spring: `en été`, `au printemps`.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Weather & seasons',
        body_markdown: 'Words for the weather and the four seasons.',
      },
    ],
    vocab: [
      { lemma_fr: 'le temps', translation_en: 'the weather', pos: 'noun', gender: 'm', ipa: 'lə tɑ̃' },
      { lemma_fr: 'le soleil', translation_en: 'the sun', pos: 'noun', gender: 'm', ipa: 'lə sɔlɛj' },
      { lemma_fr: 'la pluie', translation_en: 'the rain', pos: 'noun', gender: 'f', ipa: 'la plɥi' },
      { lemma_fr: 'le vent', translation_en: 'the wind', pos: 'noun', gender: 'm', ipa: 'lə vɑ̃' },
      { lemma_fr: 'la neige', translation_en: 'the snow', pos: 'noun', gender: 'f', ipa: 'la nɛʒ' },
      { lemma_fr: 'le nuage', translation_en: 'the cloud', pos: 'noun', gender: 'm', ipa: 'lə nɥaʒ' },
      { lemma_fr: 'chaud', translation_en: 'hot / warm', pos: 'adjective', ipa: 'ʃo' },
      { lemma_fr: 'froid', translation_en: 'cold', pos: 'adjective', ipa: 'fʁwa' },
      { lemma_fr: 'le printemps', translation_en: 'spring', pos: 'noun', gender: 'm', ipa: 'lə pʁɛ̃tɑ̃' },
      { lemma_fr: "l'été", translation_en: 'summer', pos: 'noun', gender: 'm', ipa: 'lete' },
      { lemma_fr: "l'automne", translation_en: 'autumn', pos: 'noun', gender: 'm', ipa: 'lotɔn' },
      { lemma_fr: "l'hiver", translation_en: 'winter', pos: 'noun', gender: 'm', ipa: 'livɛʁ' },
    ],
    sentences: [
      { text_fr: "Aujourd'hui, il fait beau.", text_en: 'Today the weather is nice.' },
      { text_fr: 'En hiver, il fait froid.', text_en: 'In winter, it is cold.' },
      { text_fr: 'Il pleut depuis ce matin.', text_en: 'It has been raining since this morning.' },
      { text_fr: "Il y a du vent aujourd'hui.", text_en: 'It is windy today.' },
      { text_fr: "En été, il fait très chaud.", text_en: 'In summer, it is very hot.' },
      { text_fr: 'Il neige en montagne.', text_en: 'It is snowing in the mountains.' },
      { text_fr: 'Le soleil brille au printemps.', text_en: 'The sun shines in spring.' },
      { text_fr: 'Quel temps fait-il ?', text_en: 'What is the weather like?' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-clothing',
    title_en: 'Clothing',
    title_fr: 'Les vêtements',
    theme: 'clothing',
    grammar_focus: '«porter»; demonstratives ce / cet / cette / ces',
    description:
      'Say what people are wearing and point things out with "this" and "these" (ce, cette, ces).',
    lessons: [
      {
        type: 'grammar',
        title: 'This and these',
        body_markdown: [
          '## Demonstrative adjectives',
          '',
          'To say **this / that / these**, use:',
          '',
          '- **ce** — before a masculine noun: `ce pull`',
          '- **cet** — before a masculine noun starting with a vowel: `cet homme`',
          '- **cette** — before a feminine noun: `cette robe`',
          '- **ces** — before any plural: `ces chaussures`',
          '',
          '## «porter» — to wear',
          '',
          '`porter` is a regular -er verb: `je porte`, `tu portes`, `elle porte une jupe`.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Clothes',
        body_markdown: 'Everyday clothing items.',
      },
    ],
    vocab: [
      { lemma_fr: 'les vêtements', translation_en: 'the clothes', pos: 'noun', gender: 'm', ipa: 'le vɛtmɑ̃' },
      { lemma_fr: 'le pantalon', translation_en: 'the trousers', pos: 'noun', gender: 'm', ipa: 'lə pɑ̃talɔ̃' },
      { lemma_fr: 'la chemise', translation_en: 'the shirt', pos: 'noun', gender: 'f', ipa: 'la ʃəmiz' },
      { lemma_fr: 'la robe', translation_en: 'the dress', pos: 'noun', gender: 'f', ipa: 'la ʁɔb' },
      { lemma_fr: 'la jupe', translation_en: 'the skirt', pos: 'noun', gender: 'f', ipa: 'la ʒyp' },
      { lemma_fr: 'le manteau', translation_en: 'the coat', pos: 'noun', gender: 'm', ipa: 'lə mɑ̃to' },
      { lemma_fr: 'les chaussures', translation_en: 'the shoes', pos: 'noun', gender: 'f', ipa: 'le ʃosyʁ' },
      { lemma_fr: 'le chapeau', translation_en: 'the hat', pos: 'noun', gender: 'm', ipa: 'lə ʃapo' },
      { lemma_fr: 'le pull', translation_en: 'the jumper', pos: 'noun', gender: 'm', ipa: 'lə pyl' },
      { lemma_fr: 'la veste', translation_en: 'the jacket', pos: 'noun', gender: 'f', ipa: 'la vɛst' },
      { lemma_fr: 'les chaussettes', translation_en: 'the socks', pos: 'noun', gender: 'f', ipa: 'le ʃosɛt' },
      { lemma_fr: 'porter', translation_en: 'to wear', pos: 'verb', ipa: 'pɔʁte' },
    ],
    sentences: [
      { text_fr: 'Elle porte une robe bleue.', text_en: 'She is wearing a blue dress.' },
      { text_fr: "J'aime cette chemise blanche.", text_en: 'I like this white shirt.' },
      { text_fr: 'Ces chaussures sont trop petites.', text_en: 'These shoes are too small.' },
      { text_fr: 'Il fait froid, prends ton manteau.', text_en: 'It is cold, take your coat.' },
      { text_fr: 'Ce pantalon est trop cher.', text_en: 'These trousers are too expensive.' },
      { text_fr: 'Je cherche un chapeau noir.', text_en: 'I am looking for a black hat.' },
      { text_fr: 'Tu portes un beau pull.', text_en: 'You are wearing a nice jumper.' },
      { text_fr: 'Ces vêtements sont neufs.', text_en: 'These clothes are new.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-body',
    title_en: 'The Body & Health',
    title_fr: 'Le corps et la santé',
    theme: 'health',
    grammar_focus: 'body parts; «avoir mal à» for aches and pains',
    description:
      'Name the parts of the body and say what hurts with the essential health phrase «avoir mal à».',
    lessons: [
      {
        type: 'grammar',
        title: 'Saying what hurts',
        body_markdown: [
          '## «avoir mal à»',
          '',
          'To say something hurts, use **avoir mal à** + the body part. The `à` combines with the article:',
          '',
          '- à + le → **au**: `J\'ai mal au dos.` (My back hurts.)',
          '- à + la → **à la**: `J\'ai mal à la tête.` (I have a headache.)',
          '- à + les → **aux**: `J\'ai mal aux pieds.` (My feet hurt.)',
          '',
          '## Being ill',
          '',
          '`Je suis malade.` (I am ill.) · `Je vais chez le médecin.` (I am going to the doctor\'s.)',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'The body',
        body_markdown: 'Parts of the body and health words.',
      },
    ],
    vocab: [
      { lemma_fr: 'le corps', translation_en: 'the body', pos: 'noun', gender: 'm', ipa: 'lə kɔʁ' },
      { lemma_fr: 'la tête', translation_en: 'the head', pos: 'noun', gender: 'f', ipa: 'la tɛt' },
      { lemma_fr: 'le bras', translation_en: 'the arm', pos: 'noun', gender: 'm', ipa: 'lə bʁa' },
      { lemma_fr: 'la jambe', translation_en: 'the leg', pos: 'noun', gender: 'f', ipa: 'la ʒɑ̃b' },
      { lemma_fr: 'la main', translation_en: 'the hand', pos: 'noun', gender: 'f', ipa: 'la mɛ̃' },
      { lemma_fr: 'le pied', translation_en: 'the foot', pos: 'noun', gender: 'm', ipa: 'lə pje' },
      { lemma_fr: 'les yeux', translation_en: 'the eyes', pos: 'noun', gender: 'm', ipa: 'le zjø' },
      { lemma_fr: 'la bouche', translation_en: 'the mouth', pos: 'noun', gender: 'f', ipa: 'la buʃ' },
      { lemma_fr: 'le nez', translation_en: 'the nose', pos: 'noun', gender: 'm', ipa: 'lə ne' },
      { lemma_fr: 'le ventre', translation_en: 'the stomach', pos: 'noun', gender: 'm', ipa: 'lə vɑ̃tʁ' },
      { lemma_fr: 'malade', translation_en: 'ill / sick', pos: 'adjective', ipa: 'malad' },
      { lemma_fr: 'le médecin', translation_en: 'the doctor', pos: 'noun', gender: 'm', ipa: 'lə medsɛ̃' },
    ],
    sentences: [
      { text_fr: "J'ai mal à la tête.", text_en: 'I have a headache.' },
      { text_fr: 'Il a mal au ventre.', text_en: 'He has a stomach ache.' },
      { text_fr: 'Elle est malade aujourd\'hui.', text_en: 'She is ill today.' },
      { text_fr: 'Je vais chez le médecin.', text_en: "I am going to the doctor's." },
      { text_fr: "J'ai mal aux pieds après la marche.", text_en: 'My feet hurt after the walk.' },
      { text_fr: 'Ferme les yeux et repose-toi.', text_en: 'Close your eyes and rest.' },
      { text_fr: 'Le bébé a une petite main.', text_en: 'The baby has a small hand.' },
      { text_fr: 'Mon frère a mal au bras.', text_en: 'My brother has a sore arm.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-directions',
    title_en: 'In Town: Places & Directions',
    title_fr: 'En ville : lieux et directions',
    theme: 'travel',
    grammar_focus: 'places in town; asking and giving directions',
    description:
      'Find your way around town — name the key places and ask for and give simple directions.',
    lessons: [
      {
        type: 'grammar',
        title: 'Asking the way',
        body_markdown: [
          '## Asking',
          '',
          '`Où est la gare ?` (Where is the station?) · `Pour aller au musée, s\'il vous plaît ?` (How do I get to the museum?)',
          '',
          '## Giving directions',
          '',
          '- **tout droit** — straight ahead',
          '- **à droite** — (to the) right · **à gauche** — (to the) left',
          '- **à côté de** — next to · **en face de** — opposite',
          '- **près de** — near · **loin de** — far from',
          '',
          '`Prends la première rue à droite.` — Take the first street on the right.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Places & directions',
        body_markdown: 'Key places in a town and direction words.',
      },
    ],
    vocab: [
      { lemma_fr: 'la rue', translation_en: 'the street', pos: 'noun', gender: 'f', ipa: 'la ʁy' },
      { lemma_fr: 'la gare', translation_en: 'the train station', pos: 'noun', gender: 'f', ipa: 'la ɡaʁ' },
      { lemma_fr: 'la banque', translation_en: 'the bank', pos: 'noun', gender: 'f', ipa: 'la bɑ̃k' },
      { lemma_fr: 'la pharmacie', translation_en: 'the pharmacy', pos: 'noun', gender: 'f', ipa: 'la faʁmasi' },
      { lemma_fr: "l'hôpital", translation_en: 'the hospital', pos: 'noun', gender: 'm', ipa: 'lopital' },
      { lemma_fr: "l'hôtel", translation_en: 'the hotel', pos: 'noun', gender: 'm', ipa: 'lotɛl' },
      { lemma_fr: 'le restaurant', translation_en: 'the restaurant', pos: 'noun', gender: 'm', ipa: 'lə ʁɛstɔʁɑ̃' },
      { lemma_fr: 'la place', translation_en: 'the square', pos: 'noun', gender: 'f', ipa: 'la plas' },
      { lemma_fr: 'le musée', translation_en: 'the museum', pos: 'noun', gender: 'm', ipa: 'lə myze' },
      { lemma_fr: 'à droite', translation_en: 'on the right', pos: 'phrase', ipa: 'a dʁwat' },
      { lemma_fr: 'à gauche', translation_en: 'on the left', pos: 'phrase', ipa: 'a ɡoʃ' },
      { lemma_fr: 'tout droit', translation_en: 'straight ahead', pos: 'phrase', ipa: 'tu dʁwa' },
    ],
    sentences: [
      { text_fr: 'Où est la gare ?', text_en: 'Where is the station?' },
      { text_fr: 'La banque est à droite.', text_en: 'The bank is on the right.' },
      { text_fr: 'Continuez tout droit.', text_en: 'Continue straight ahead.' },
      { text_fr: "La pharmacie est en face de l'hôtel.", text_en: 'The pharmacy is opposite the hotel.' },
      { text_fr: 'Le musée est près de la place.', text_en: 'The museum is near the square.' },
      { text_fr: 'Prenez la première rue à gauche.', text_en: 'Take the first street on the left.' },
      { text_fr: "L'hôpital est loin d'ici.", text_en: 'The hospital is far from here.' },
      { text_fr: 'Il y a un bon restaurant dans cette rue.', text_en: 'There is a good restaurant on this street.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-hobbies',
    title_en: 'Hobbies & Free Time',
    title_fr: 'Les loisirs',
    theme: 'leisure',
    grammar_focus: 'aimer + infinitive; «faire du/de la», «jouer à/de»',
    description:
      'Say what you like doing in your free time, and learn the two verbs French uses for activities: faire and jouer.',
    lessons: [
      {
        type: 'grammar',
        title: 'Talking about activities',
        body_markdown: [
          '## Liking to do something',
          '',
          'Use a liking verb + the **infinitive**: `J\'aime lire.` (I like to read.) `Elle adore voyager.` `Je déteste courir.`',
          '',
          '## «faire du / de la»',
          '',
          'For many sports and activities French uses **faire**: `faire du sport`, `faire de la musique`, `faire du vélo`.',
          '',
          '## «jouer à» vs «jouer de»',
          '',
          '- **jouer à** — games and sports: `jouer au football`, `jouer au tennis`.',
          '- **jouer de** — musical instruments: `jouer du piano`, `jouer de la guitare`.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Hobbies',
        body_markdown: 'Activities and free-time words.',
      },
    ],
    vocab: [
      { lemma_fr: 'le sport', translation_en: 'sport', pos: 'noun', gender: 'm', ipa: 'lə spɔʁ' },
      { lemma_fr: 'la musique', translation_en: 'music', pos: 'noun', gender: 'f', ipa: 'la myzik' },
      { lemma_fr: 'le cinéma', translation_en: 'the cinema', pos: 'noun', gender: 'm', ipa: 'lə sinema' },
      { lemma_fr: 'la lecture', translation_en: 'reading', pos: 'noun', gender: 'f', ipa: 'la lɛktyʁ' },
      { lemma_fr: 'la danse', translation_en: 'dance', pos: 'noun', gender: 'f', ipa: 'la dɑ̃s' },
      { lemma_fr: 'le football', translation_en: 'football', pos: 'noun', gender: 'm', ipa: 'lə futbol' },
      { lemma_fr: 'le tennis', translation_en: 'tennis', pos: 'noun', gender: 'm', ipa: 'lə tenis' },
      { lemma_fr: 'la guitare', translation_en: 'the guitar', pos: 'noun', gender: 'f', ipa: 'la ɡitaʁ' },
      { lemma_fr: 'le piano', translation_en: 'the piano', pos: 'noun', gender: 'm', ipa: 'lə pjano' },
      { lemma_fr: 'nager', translation_en: 'to swim', pos: 'verb', ipa: 'naʒe' },
      { lemma_fr: 'lire', translation_en: 'to read', pos: 'verb', ipa: 'liʁ' },
      { lemma_fr: 'voyager', translation_en: 'to travel', pos: 'verb', ipa: 'vwajaʒe' },
    ],
    sentences: [
      { text_fr: "J'aime jouer au football.", text_en: 'I like to play football.' },
      { text_fr: 'Elle joue du piano le soir.', text_en: 'She plays the piano in the evening.' },
      { text_fr: 'Nous faisons du sport le week-end.', text_en: 'We do sport at the weekend.' },
      { text_fr: 'Il adore lire des livres.', text_en: 'He loves reading books.' },
      { text_fr: 'Tu aimes voyager en Europe ?', text_en: 'Do you like travelling in Europe?' },
      { text_fr: 'Je vais au cinéma avec des amis.', text_en: 'I am going to the cinema with friends.' },
      { text_fr: 'Ma sœur fait de la danse.', text_en: 'My sister does dance.' },
      { text_fr: "J'écoute de la musique quand je travaille.", text_en: 'I listen to music when I work.' },
    ],
  },

  {
    level: 'A1',
    slug: 'a1-shopping',
    title_en: 'Shopping',
    title_fr: 'Les courses',
    theme: 'shopping',
    grammar_focus: 'prices and quantities; «acheter», «combien»',
    description:
      'Go shopping in French — ask prices, say how much things cost, and handle a simple purchase.',
    lessons: [
      {
        type: 'grammar',
        title: 'Prices and buying',
        body_markdown: [
          '## Asking the price',
          '',
          '- `C\'est combien ?` / `Combien ça coûte ?` — How much is it?',
          '- `Ça fait dix euros.` — That comes to ten euros.',
          '- `Je voudrais…` / `Je prends…` — I would like… / I\'ll take…',
          '',
          '## «acheter» — a spelling-change verb',
          '',
          'Most forms add a grave accent: `j\'achète`, `tu achètes`, `il achète`, but `nous achetons`, `vous achetez`. The stressed **è** gives the "eh" sound.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Shopping words',
        body_markdown: 'Words for shops, money and buying.',
      },
    ],
    vocab: [
      { lemma_fr: 'le magasin', translation_en: 'the shop', pos: 'noun', gender: 'm', ipa: 'lə maɡazɛ̃' },
      { lemma_fr: 'le marché', translation_en: 'the market', pos: 'noun', gender: 'm', ipa: 'lə maʁʃe' },
      { lemma_fr: 'le prix', translation_en: 'the price', pos: 'noun', gender: 'm', ipa: 'lə pʁi' },
      { lemma_fr: "l'argent", translation_en: 'the money', pos: 'noun', gender: 'm', ipa: 'laʁʒɑ̃' },
      { lemma_fr: "l'euro", translation_en: 'the euro', pos: 'noun', gender: 'm', ipa: 'løʁo' },
      { lemma_fr: 'la carte', translation_en: 'the (bank) card', pos: 'noun', gender: 'f', ipa: 'la kaʁt' },
      { lemma_fr: 'cher', translation_en: 'expensive', pos: 'adjective', ipa: 'ʃɛʁ' },
      { lemma_fr: 'bon marché', translation_en: 'cheap', pos: 'adjective', ipa: 'bɔ̃ maʁʃe' },
      { lemma_fr: 'acheter', translation_en: 'to buy', pos: 'verb', ipa: 'aʃte' },
      { lemma_fr: 'payer', translation_en: 'to pay', pos: 'verb', ipa: 'peje' },
      { lemma_fr: 'coûter', translation_en: 'to cost', pos: 'verb', ipa: 'kute' },
      { lemma_fr: 'le client', translation_en: 'the customer', pos: 'noun', gender: 'm', ipa: 'lə klijɑ̃' },
    ],
    sentences: [
      { text_fr: "C'est combien ?", text_en: 'How much is it?' },
      { text_fr: 'Ça fait quinze euros.', text_en: 'That comes to fifteen euros.' },
      { text_fr: "J'achète du pain au marché.", text_en: 'I buy bread at the market.' },
      { text_fr: 'Cette veste est trop chère.', text_en: 'This jacket is too expensive.' },
      { text_fr: 'Je paie par carte.', text_en: 'I am paying by card.' },
      { text_fr: 'Combien coûte ce livre ?', text_en: 'How much does this book cost?' },
      { text_fr: 'Les légumes sont bon marché ici.', text_en: 'The vegetables are cheap here.' },
      { text_fr: "Le client cherche un cadeau.", text_en: 'The customer is looking for a gift.' },
    ],
  },
];
