/*
 * A2 curriculum units (14). Builds on A1 with the first "real" tenses — the passé
 * composé (with avoir and être), the imparfait, and the futur proche — plus the
 * grammar (reflexives, object & y/en pronouns, negation, comparatives, partitives,
 * connectors) and everyday topics (routine, travel, restaurant, shopping, health)
 * that use them. Same authoring model as a1.ts: lessons + vocab + sentences, with
 * a few hand-authored drills where the grammar needs targeting.
 */

import type { UnitDef } from './types';

export const a2Units: UnitDef[] = [
  {
    level: 'A2',
    slug: 'a2-passe-compose-avoir',
    title_en: 'The Past: Passé Composé with avoir',
    title_fr: 'Le passé composé avec avoir',
    theme: 'grammar',
    grammar_focus: 'passé composé with avoir; past participles',
    description:
      'Talk about completed actions in the past. Learn the most common French past tense: avoir in the present plus a past participle.',
    lessons: [
      {
        type: 'grammar',
        title: 'Forming the passé composé',
        body_markdown: [
          '## Two pieces: avoir + past participle',
          '',
          'The passé composé describes a **completed** past action ("I ate", "I have eaten"). Most verbs build it with the present tense of **avoir** plus a **past participle**:',
          '',
          '- **j\'ai** parlé — I spoke',
          '- **tu as** mangé — you ate',
          '- **il/elle a** fini — he/she finished',
          '- **nous avons** vendu — we sold',
          '- **vous avez** pris — you took',
          '- **ils/elles ont** fait — they did',
          '',
          '## Making the past participle',
          '',
          '- **-er** verbs → **-é**: parler → `parlé`, manger → `mangé`',
          '- **-ir** verbs → **-i**: finir → `fini`, choisir → `choisi`',
          '- **-re** verbs → **-u**: vendre → `vendu`, attendre → `attendu`',
          '',
          '## Common irregular participles',
          '',
          '`faire → fait`, `voir → vu`, `prendre → pris`, `avoir → eu`, `être → été`, `boire → bu`, `écrire → écrit`, `comprendre → compris`.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Verbs for the past',
        body_markdown: 'Common verbs you will put into the passé composé.',
      },
    ],
    vocab: [
      { lemma_fr: 'manger', translation_en: 'to eat', pos: 'verb', ipa: 'mɑ̃ʒe' },
      { lemma_fr: 'finir', translation_en: 'to finish', pos: 'verb', ipa: 'finiʁ' },
      { lemma_fr: 'choisir', translation_en: 'to choose', pos: 'verb', ipa: 'ʃwaziʁ' },
      { lemma_fr: 'vendre', translation_en: 'to sell', pos: 'verb', ipa: 'vɑ̃dʁ' },
      { lemma_fr: 'attendre', translation_en: 'to wait (for)', pos: 'verb', ipa: 'atɑ̃dʁ' },
      { lemma_fr: 'faire', translation_en: 'to do / to make', pos: 'verb', ipa: 'fɛʁ' },
      { lemma_fr: 'voir', translation_en: 'to see', pos: 'verb', ipa: 'vwaʁ' },
      { lemma_fr: 'prendre', translation_en: 'to take', pos: 'verb', ipa: 'pʁɑ̃dʁ' },
      { lemma_fr: 'boire', translation_en: 'to drink', pos: 'verb', ipa: 'bwaʁ' },
      { lemma_fr: 'écrire', translation_en: 'to write', pos: 'verb', ipa: 'ekʁiʁ' },
      { lemma_fr: 'comprendre', translation_en: 'to understand', pos: 'verb', ipa: 'kɔ̃pʁɑ̃dʁ' },
      { lemma_fr: 'hier', translation_en: 'yesterday', pos: 'adverb', ipa: 'jɛʁ' },
      { lemma_fr: 'la semaine dernière', translation_en: 'last week', pos: 'phrase', ipa: 'la səmɛn dɛʁnjɛʁ' },
    ],
    sentences: [
      { text_fr: "J'ai mangé une pizza hier soir.", text_en: 'I ate a pizza last night.' },
      { text_fr: 'Tu as fini tes devoirs ?', text_en: 'Have you finished your homework?' },
      { text_fr: 'Nous avons vu un bon film.', text_en: 'We saw a good film.' },
      { text_fr: 'Elle a pris le train ce matin.', text_en: 'She took the train this morning.' },
      { text_fr: 'Ils ont acheté une nouvelle voiture.', text_en: 'They bought a new car.' },
      { text_fr: "J'ai bu un café au petit-déjeuner.", text_en: 'I drank a coffee at breakfast.' },
      { text_fr: 'Vous avez compris la leçon ?', text_en: 'Did you understand the lesson?' },
      { text_fr: 'Il a écrit une longue lettre.', text_en: 'He wrote a long letter.' },
    ],
    exercises: [
      { type: 'cloze', prompt: "Hier, j' ____ mangé une pomme. (avoir)", answer: 'ai', accepted_alternatives: ['ai'] },
      { type: 'cloze', prompt: 'Nous avons ____ un film hier soir. (voir)', answer: 'vu', accepted_alternatives: ['vu'] },
      { type: 'cloze', prompt: 'Elle a ____ le train ce matin. (prendre)', answer: 'pris', accepted_alternatives: ['pris'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-passe-compose-etre',
    title_en: 'The Past: Passé Composé with être',
    title_fr: 'Le passé composé avec être',
    theme: 'grammar',
    grammar_focus: 'passé composé with être; participle agreement',
    description:
      'A small group of verbs — mostly about movement — form the past with être instead of avoir, and their participle agrees with the subject.',
    lessons: [
      {
        type: 'grammar',
        title: 'When to use être',
        body_markdown: [
          '## A special group of verbs',
          '',
          'About a dozen verbs of **movement or change of state** use **être** (not avoir) in the passé composé: `aller, venir, arriver, partir, entrer, sortir, monter, descendre, rester, tomber, naître, mourir`.',
          '',
          '- je **suis** allé — I went',
          '- elle **est** arrivée — she arrived',
          '- nous **sommes** partis — we left',
          '',
          '## The participle agrees',
          '',
          'With être, the past participle **agrees with the subject** — add **-e** for feminine, **-s** for plural:',
          '',
          '- `Il est allé.` → `Elle est allé**e**.`',
          '- `Ils sont venu**s**.` → `Elles sont venu**es**.`',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Movement verbs',
        body_markdown: 'The core être verbs (movement and change of state).',
      },
    ],
    vocab: [
      { lemma_fr: 'aller', translation_en: 'to go', pos: 'verb', ipa: 'ale' },
      { lemma_fr: 'venir', translation_en: 'to come', pos: 'verb', ipa: 'vəniʁ' },
      { lemma_fr: 'arriver', translation_en: 'to arrive', pos: 'verb', ipa: 'aʁive' },
      { lemma_fr: 'partir', translation_en: 'to leave', pos: 'verb', ipa: 'paʁtiʁ' },
      { lemma_fr: 'entrer', translation_en: 'to enter', pos: 'verb', ipa: 'ɑ̃tʁe' },
      { lemma_fr: 'sortir', translation_en: 'to go out', pos: 'verb', ipa: 'sɔʁtiʁ' },
      { lemma_fr: 'monter', translation_en: 'to go up / get on', pos: 'verb', ipa: 'mɔ̃te' },
      { lemma_fr: 'descendre', translation_en: 'to go down / get off', pos: 'verb', ipa: 'desɑ̃dʁ' },
      { lemma_fr: 'rester', translation_en: 'to stay', pos: 'verb', ipa: 'ʁɛste' },
      { lemma_fr: 'tomber', translation_en: 'to fall', pos: 'verb', ipa: 'tɔ̃be' },
      { lemma_fr: 'retourner', translation_en: 'to return', pos: 'verb', ipa: 'ʁətuʁne' },
      { lemma_fr: 'en retard', translation_en: 'late', pos: 'phrase', ipa: 'ɑ̃ ʁətaʁ' },
    ],
    sentences: [
      { text_fr: 'Je suis allé au marché.', text_en: 'I went to the market.' },
      { text_fr: 'Elle est arrivée en retard.', text_en: 'She arrived late.' },
      { text_fr: 'Nous sommes partis à huit heures.', text_en: 'We left at eight.' },
      { text_fr: 'Ils sont venus chez moi.', text_en: 'They came to my place.' },
      { text_fr: 'Elle est restée à la maison.', text_en: 'She stayed at home.' },
      { text_fr: 'Le train est parti sans moi.', text_en: 'The train left without me.' },
      { text_fr: 'Tu es sorti hier soir ?', text_en: 'Did you go out last night?' },
      { text_fr: 'Elles sont montées dans le bus.', text_en: 'They got on the bus.' },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Elle ____ allée au cinéma. (être)', answer: 'est', accepted_alternatives: ['est'] },
      { type: 'cloze', prompt: 'Nous sommes ____ à huit heures. (partir)', answer: 'partis', accepted_alternatives: ['partis'] },
      { type: 'cloze', prompt: 'Ils sont ____ chez moi. (venir)', answer: 'venus', accepted_alternatives: ['venus'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-imparfait',
    title_en: 'The Imperfect: L\'imparfait',
    title_fr: "L'imparfait",
    theme: 'grammar',
    grammar_focus: 'the imparfait for descriptions and habits in the past',
    description:
      'Describe how things used to be and what was happening. The imparfait is the past tense for descriptions, habits, and background.',
    lessons: [
      {
        type: 'grammar',
        title: 'Forming and using the imparfait',
        body_markdown: [
          '## How to form it',
          '',
          'Take the **nous** form of the present, drop **-ons**, and add the imparfait endings:',
          '',
          '`nous parlons` → stem `parl-` → **je parlais, tu parlais, il parlait, nous parlions, vous parliez, ils parlaient**.',
          '',
          'Only **être** is irregular: `j\'étais, tu étais, il était…`',
          '',
          '## When to use it',
          '',
          'The imparfait is for the **background** of the past:',
          '',
          '- habits ("used to"): `Je jouais au tennis le samedi.`',
          '- descriptions: `Il faisait beau, les oiseaux chantaient.`',
          '- ongoing actions ("was ...-ing"): `Je regardais la télé quand tu as appelé.`',
          '',
          '> Rule of thumb: **passé composé** = what happened (an event); **imparfait** = what was going on (the setting).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Words for the past',
        body_markdown: 'Verbs and time words often used with the imparfait.',
      },
    ],
    vocab: [
      { lemma_fr: 'être', translation_en: 'to be', pos: 'verb', ipa: 'ɛtʁ' },
      { lemma_fr: 'avoir', translation_en: 'to have', pos: 'verb', ipa: 'avwaʁ' },
      { lemma_fr: 'vouloir', translation_en: 'to want', pos: 'verb', ipa: 'vulwaʁ' },
      { lemma_fr: 'pouvoir', translation_en: 'to be able to', pos: 'verb', ipa: 'puvwaʁ' },
      { lemma_fr: 'souvent', translation_en: 'often', pos: 'adverb', ipa: 'suvɑ̃' },
      { lemma_fr: 'toujours', translation_en: 'always', pos: 'adverb', ipa: 'tuʒuʁ' },
      { lemma_fr: 'autrefois', translation_en: 'in the past / formerly', pos: 'adverb', ipa: 'otʁəfwa' },
      { lemma_fr: 'quelquefois', translation_en: 'sometimes', pos: 'adverb', ipa: 'kɛlkəfwa' },
      { lemma_fr: 'chaque', translation_en: 'each / every', pos: 'adjective', ipa: 'ʃak' },
      { lemma_fr: 'jeune', translation_en: 'young', pos: 'adjective', ipa: 'ʒœn' },
      { lemma_fr: 'heureux', translation_en: 'happy', pos: 'adjective', ipa: 'œʁø' },
      { lemma_fr: 'la campagne', translation_en: 'the countryside', pos: 'noun', gender: 'f', ipa: 'la kɑ̃paɲ' },
    ],
    sentences: [
      { text_fr: "Quand j'étais petit, j'habitais à Lyon.", text_en: 'When I was little, I lived in Lyon.' },
      { text_fr: 'Elle jouait souvent au tennis.', text_en: 'She often played tennis.' },
      { text_fr: 'Il faisait beau ce jour-là.', text_en: 'The weather was nice that day.' },
      { text_fr: 'Nous allions à la plage chaque été.', text_en: 'We went to the beach every summer.' },
      { text_fr: 'Je voulais devenir médecin.', text_en: 'I wanted to become a doctor.' },
      { text_fr: 'Ils avaient un grand jardin.', text_en: 'They had a big garden.' },
      { text_fr: 'Tu regardais la télé quand j\'ai appelé.', text_en: 'You were watching TV when I called.' },
      { text_fr: 'Autrefois, les gens écrivaient des lettres.', text_en: 'In the past, people wrote letters.' },
    ],
    exercises: [
      { type: 'cloze', prompt: "Quand j'étais petit, j' ____ à Lyon. (habiter)", answer: 'habitais', accepted_alternatives: ['habitais'] },
      { type: 'cloze', prompt: 'Il ____ beau ce jour-là. (faire)', answer: 'faisait', accepted_alternatives: ['faisait'] },
      { type: 'cloze', prompt: 'Nous ____ à la plage chaque été. (aller)', answer: 'allions', accepted_alternatives: ['allions'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-futur-proche',
    title_en: 'The Near Future: Futur Proche',
    title_fr: 'Le futur proche',
    theme: 'grammar',
    grammar_focus: 'the near future: aller + infinitive',
    description:
      'Say what you are going to do. The near future is simple: aller in the present plus an infinitive.',
    lessons: [
      {
        type: 'grammar',
        title: 'Going to do something',
        body_markdown: [
          '## aller + infinitive',
          '',
          'To talk about the near future, use the present of **aller** plus an **infinitive** — just like English "going to":',
          '',
          '- **je vais** manger — I am going to eat',
          '- **tu vas** partir — you are going to leave',
          '- **il/elle va** commencer — he/she is going to start',
          '- **nous allons** visiter — we are going to visit',
          '- **vous allez** voir — you are going to see',
          '- **ils/elles vont** rester — they are going to stay',
          '',
          '## Negative',
          '',
          'Wrap **ne … pas** around the form of aller: `Je **ne** vais **pas** rester.` (I am not going to stay.)',
          '',
          'Useful time markers: `demain`, `ce soir`, `la semaine prochaine`, `bientôt`.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Future plans',
        body_markdown: 'Verbs and time words for talking about plans.',
      },
    ],
    vocab: [
      { lemma_fr: 'aller', translation_en: 'to go (going to)', pos: 'verb', ipa: 'ale' },
      { lemma_fr: 'visiter', translation_en: 'to visit', pos: 'verb', ipa: 'vizite' },
      { lemma_fr: 'commencer', translation_en: 'to start', pos: 'verb', ipa: 'kɔmɑ̃se' },
      { lemma_fr: 'rencontrer', translation_en: 'to meet', pos: 'verb', ipa: 'ʁɑ̃kɔ̃tʁe' },
      { lemma_fr: 'préparer', translation_en: 'to prepare', pos: 'verb', ipa: 'pʁepaʁe' },
      { lemma_fr: 'demain', translation_en: 'tomorrow', pos: 'adverb', ipa: 'dəmɛ̃' },
      { lemma_fr: 'ce soir', translation_en: 'this evening', pos: 'phrase', ipa: 'sə swaʁ' },
      { lemma_fr: 'la semaine prochaine', translation_en: 'next week', pos: 'phrase', ipa: 'la səmɛn pʁɔʃɛn' },
      { lemma_fr: 'bientôt', translation_en: 'soon', pos: 'adverb', ipa: 'bjɛ̃to' },
      { lemma_fr: 'plus tard', translation_en: 'later', pos: 'phrase', ipa: 'ply taʁ' },
      { lemma_fr: "l'année prochaine", translation_en: 'next year', pos: 'phrase', ipa: 'lane pʁɔʃɛn' },
      { lemma_fr: 'le projet', translation_en: 'the plan / project', pos: 'noun', gender: 'm', ipa: 'lə pʁɔʒɛ' },
    ],
    sentences: [
      { text_fr: 'Je vais manger au restaurant ce soir.', text_en: 'I am going to eat at a restaurant tonight.' },
      { text_fr: 'Nous allons visiter Paris la semaine prochaine.', text_en: 'We are going to visit Paris next week.' },
      { text_fr: 'Tu vas partir bientôt ?', text_en: 'Are you going to leave soon?' },
      { text_fr: 'Elle va commencer un nouveau travail.', text_en: 'She is going to start a new job.' },
      { text_fr: 'Ils vont acheter une maison.', text_en: 'They are going to buy a house.' },
      { text_fr: 'Il va pleuvoir demain.', text_en: 'It is going to rain tomorrow.' },
      { text_fr: 'Je ne vais pas rester ici.', text_en: 'I am not going to stay here.' },
      { text_fr: 'Nous allons rencontrer nos amis.', text_en: 'We are going to meet our friends.' },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Je ____ manger au restaurant ce soir. (aller)', answer: 'vais', accepted_alternatives: ['vais'] },
      { type: 'cloze', prompt: 'Nous allons ____ Paris demain. (visiter)', answer: 'visiter', accepted_alternatives: ['visiter'] },
      { type: 'cloze', prompt: 'Ils ____ acheter une maison. (aller)', answer: 'vont', accepted_alternatives: ['vont'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-daily-routine',
    title_en: 'Daily Routine: Reflexive Verbs',
    title_fr: 'La routine quotidienne',
    theme: 'daily life',
    grammar_focus: 'reflexive (pronominal) verbs in the present',
    description:
      'Describe your day from morning to night. Reflexive verbs use an extra pronoun (me, te, se…) for actions you do to yourself.',
    lessons: [
      {
        type: 'grammar',
        title: 'Reflexive verbs',
        body_markdown: [
          '## An extra pronoun',
          '',
          'Reflexive verbs describe an action done **to oneself** (to get up, to wash). They carry a reflexive pronoun that matches the subject:',
          '',
          '- **je me** lève — I get up',
          '- **tu te** laves — you wash',
          '- **il/elle se** couche — he/she goes to bed',
          '- **nous nous** levons — we get up',
          '- **vous vous** habillez — you get dressed',
          '- **ils/elles se** reposent — they rest',
          '',
          'Before a vowel, **me/te/se** shorten: `je m\'habille`, `tu t\'appelles`, `il s\'endort`.',
          '',
          '## Order of the day',
          '',
          'Sequence your routine with `d\'abord` (first), `ensuite` / `puis` (then), `enfin` (finally). In commands, the pronoun follows: `Lève-**toi** !` (Get up!), `Dépêchons-**nous** !` (Let\'s hurry!).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Routine verbs',
        body_markdown: 'The reflexive verbs and time words of an everyday routine.',
      },
    ],
    vocab: [
      { lemma_fr: 'se lever', translation_en: 'to get up', pos: 'verb', ipa: 'sə ləve' },
      { lemma_fr: 'se réveiller', translation_en: 'to wake up', pos: 'verb', ipa: 'sə ʁevɛje' },
      { lemma_fr: 'se laver', translation_en: 'to wash (oneself)', pos: 'verb', ipa: 'sə lave' },
      { lemma_fr: "s'habiller", translation_en: 'to get dressed', pos: 'verb', ipa: 'sabije' },
      { lemma_fr: 'se brosser', translation_en: 'to brush', pos: 'verb', ipa: 'sə bʁɔse' },
      { lemma_fr: 'se coucher', translation_en: 'to go to bed', pos: 'verb', ipa: 'sə kuʃe' },
      { lemma_fr: 'se reposer', translation_en: 'to rest', pos: 'verb', ipa: 'sə ʁəpoze' },
      { lemma_fr: 'se dépêcher', translation_en: 'to hurry', pos: 'verb', ipa: 'sə depeʃe' },
      { lemma_fr: 'tôt', translation_en: 'early', pos: 'adverb', ipa: 'to' },
      { lemma_fr: 'tard', translation_en: 'late', pos: 'adverb', ipa: 'taʁ' },
      { lemma_fr: "d'abord", translation_en: 'first (of all)', pos: 'adverb', ipa: 'dabɔʁ' },
      { lemma_fr: 'ensuite', translation_en: 'then / next', pos: 'adverb', ipa: 'ɑ̃sɥit' },
    ],
    sentences: [
      { text_fr: 'Je me lève à sept heures.', text_en: 'I get up at seven.' },
      { text_fr: 'Tu te laves les mains ?', text_en: 'Are you washing your hands?' },
      { text_fr: "Il s'habille rapidement.", text_en: 'He gets dressed quickly.' },
      { text_fr: 'Nous nous couchons tard le week-end.', text_en: 'We go to bed late on weekends.' },
      { text_fr: 'Elle se brosse les dents après le petit-déjeuner.', text_en: 'She brushes her teeth after breakfast.' },
      { text_fr: "D'abord je me réveille, ensuite je prends une douche.", text_en: 'First I wake up, then I take a shower.' },
      { text_fr: 'Dépêche-toi, nous sommes en retard !', text_en: "Hurry up, we're late!" },
      { text_fr: 'Le soir, ils se reposent devant la télé.', text_en: 'In the evening, they rest in front of the TV.' },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Je ____ lève à sept heures. (reflexive pronoun)', answer: 'me', accepted_alternatives: ['me'] },
      { type: 'cloze', prompt: 'Nous ____ couchons tard. (reflexive pronoun)', answer: 'nous', accepted_alternatives: ['nous'] },
      { type: 'cloze', prompt: 'Elle se ____ les dents. (brosser)', answer: 'brosse', accepted_alternatives: ['brosse'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-object-pronouns',
    title_en: 'Object Pronouns: le, la, lui, leur',
    title_fr: 'Les pronoms compléments',
    theme: 'grammar',
    grammar_focus: 'direct and indirect object pronouns',
    description:
      'Avoid repeating names and things. Direct object pronouns (le, la, les) and indirect ones (lui, leur) go right before the verb.',
    lessons: [
      {
        type: 'grammar',
        title: 'Direct and indirect object pronouns',
        body_markdown: [
          '## Direct objects: le, la, les',
          '',
          'A direct object receives the action with **no preposition**. Replace it with **le** (m), **la** (f), **les** (pl) — placed **before the verb**:',
          '',
          '- Tu vois Marie ? — Oui, je **la** vois. (I see her.)',
          '- Je connais ces livres. — Je **les** connais.',
          '',
          '## Indirect objects: lui, leur',
          '',
          'An indirect object follows **à** (à quelqu\'un). Replace `à + person` with **lui** (to him/her) or **leur** (to them):',
          '',
          '- Je parle à Paul. — Je **lui** parle.',
          '- Je téléphone à mes parents. — Je **leur** téléphone.',
          '',
          '## me, te, nous, vous',
          '',
          'These work as both direct and indirect: `Tu **m\'**aides ?`, `Il **nous** parle.` The pronoun always sits **before the conjugated verb** (or before the infinitive: `Je vais **le** faire.`).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Verbs with objects',
        body_markdown: 'Verbs that commonly take a direct or indirect object.',
      },
    ],
    vocab: [
      { lemma_fr: 'connaître', translation_en: 'to know (a person/place)', pos: 'verb', ipa: 'kɔnɛtʁ' },
      { lemma_fr: 'aider', translation_en: 'to help', pos: 'verb', ipa: 'ede' },
      { lemma_fr: 'appeler', translation_en: 'to call', pos: 'verb', ipa: 'aple' },
      { lemma_fr: 'montrer', translation_en: 'to show', pos: 'verb', ipa: 'mɔ̃tʁe' },
      { lemma_fr: 'donner', translation_en: 'to give', pos: 'verb', ipa: 'dɔne' },
      { lemma_fr: 'envoyer', translation_en: 'to send', pos: 'verb', ipa: 'ɑ̃vwaje' },
      { lemma_fr: 'inviter', translation_en: 'to invite', pos: 'verb', ipa: 'ɛ̃vite' },
      { lemma_fr: 'téléphoner', translation_en: 'to phone', pos: 'verb', ipa: 'telefɔne' },
      { lemma_fr: 'remercier', translation_en: 'to thank', pos: 'verb', ipa: 'ʁəmɛʁsje' },
      { lemma_fr: 'le cadeau', translation_en: 'the gift', pos: 'noun', gender: 'm', ipa: 'lə kado' },
      { lemma_fr: 'le message', translation_en: 'the message', pos: 'noun', gender: 'm', ipa: 'lə mesaʒ' },
      { lemma_fr: 'la réponse', translation_en: 'the answer', pos: 'noun', gender: 'f', ipa: 'la ʁepɔ̃s' },
    ],
    sentences: [
      { text_fr: 'Tu vois Marie ? Oui, je la vois.', text_en: 'Do you see Marie? Yes, I see her.' },
      { text_fr: 'Je connais Paul ; je le connais bien.', text_en: 'I know Paul; I know him well.' },
      { text_fr: "Tu m'aides, s'il te plaît ?", text_en: 'Can you help me, please?' },
      { text_fr: 'Je lui donne un cadeau.', text_en: 'I give him/her a gift.' },
      { text_fr: 'Nous les invitons à dîner.', text_en: 'We invite them to dinner.' },
      { text_fr: 'Il nous appelle ce soir.', text_en: 'He is calling us tonight.' },
      { text_fr: 'Je leur envoie un message.', text_en: 'I send them a message.' },
      { text_fr: 'Elle te remercie beaucoup.', text_en: 'She thanks you a lot.' },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Tu vois Marie ? Oui, je ____ vois. (her)', answer: 'la', accepted_alternatives: ['la'] },
      { type: 'cloze', prompt: 'Je ____ donne un cadeau à Paul. (to him)', answer: 'lui', accepted_alternatives: ['lui'] },
      { type: 'cloze', prompt: 'Paul et Marie ? Nous ____ invitons. (them)', answer: 'les', accepted_alternatives: ['les'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-negation',
    title_en: 'Negation: jamais, rien, personne',
    title_fr: 'La négation',
    theme: 'grammar',
    grammar_focus: 'negative expressions beyond ne… pas',
    description:
      'Say never, nothing, nobody, no longer and only. These negatives wrap around the verb like ne… pas.',
    lessons: [
      {
        type: 'grammar',
        title: 'More ways to say no',
        body_markdown: [
          '## The ne … X pattern',
          '',
          'Like **ne … pas**, other negatives put **ne** before the verb and a second word after:',
          '',
          '- ne … **jamais** — never: `Je ne fume jamais.`',
          '- ne … **rien** — nothing: `Il ne mange rien.`',
          '- ne … **plus** — no longer: `Elle ne travaille plus ici.`',
          '- ne … **personne** — nobody: `Je ne vois personne.`',
          '- ne … **que** — only (not truly negative): `Je n\'ai que dix euros.`',
          '',
          '## Two things to remember',
          '',
          'After a negative, `un/une/du/de la/des` usually becomes **de**: `Je ne mange **pas de** viande.`',
          '',
          '**Personne** and **rien** can be the subject too, and then come first: `**Personne** ne comprend.`, `**Rien** n\'est facile.`',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Negative words',
        body_markdown: 'The vocabulary of negation and its opposites.',
      },
    ],
    vocab: [
      { lemma_fr: 'jamais', translation_en: 'never', pos: 'adverb', ipa: 'ʒamɛ' },
      { lemma_fr: 'rien', translation_en: 'nothing', pos: 'pronoun', ipa: 'ʁjɛ̃' },
      { lemma_fr: 'personne', translation_en: 'nobody', pos: 'pronoun', ipa: 'pɛʁsɔn' },
      { lemma_fr: 'plus', translation_en: 'no longer / anymore', pos: 'adverb', ipa: 'ply' },
      { lemma_fr: 'encore', translation_en: 'still / again', pos: 'adverb', ipa: 'ɑ̃kɔʁ' },
      { lemma_fr: 'déjà', translation_en: 'already', pos: 'adverb', ipa: 'deʒa' },
      { lemma_fr: "quelqu'un", translation_en: 'someone', pos: 'pronoun', ipa: 'kɛlkœ̃' },
      { lemma_fr: 'quelque chose', translation_en: 'something', pos: 'pronoun', ipa: 'kɛlkə ʃoz' },
      { lemma_fr: 'sans', translation_en: 'without', pos: 'preposition', ipa: 'sɑ̃' },
      { lemma_fr: 'ni', translation_en: 'nor', pos: 'conjunction', ipa: 'ni' },
      { lemma_fr: 'aucun', translation_en: 'no / not any', pos: 'adjective', ipa: 'okœ̃' },
      { lemma_fr: 'toujours', translation_en: 'still / always', pos: 'adverb', ipa: 'tuʒuʁ' },
    ],
    sentences: [
      { text_fr: 'Je ne mange jamais de viande.', text_en: 'I never eat meat.' },
      { text_fr: "Il n'y a rien dans le frigo.", text_en: "There's nothing in the fridge." },
      { text_fr: "Personne n'est venu à la fête.", text_en: 'Nobody came to the party.' },
      { text_fr: 'Je ne fume plus.', text_en: "I don't smoke anymore." },
      { text_fr: "Nous n'avons qu'une voiture.", text_en: 'We only have one car.' },
      { text_fr: "Tu n'as rien mangé ?", text_en: "You didn't eat anything?" },
      { text_fr: 'Elle ne connaît personne ici.', text_en: "She doesn't know anyone here." },
      { text_fr: "Je n'ai jamais visité l'Italie.", text_en: 'I have never visited Italy.' },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Je ne mange ____ de viande. (never)', answer: 'jamais', accepted_alternatives: ['jamais'] },
      { type: 'cloze', prompt: "Il n'y a ____ dans le frigo. (nothing)", answer: 'rien', accepted_alternatives: ['rien'] },
      { type: 'cloze', prompt: 'Je ne fume ____. (no longer)', answer: 'plus', accepted_alternatives: ['plus'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-comparatives',
    title_en: 'Comparisons: plus, moins, aussi',
    title_fr: 'Le comparatif et le superlatif',
    theme: 'grammar',
    grammar_focus: 'comparatives and superlatives of adjectives',
    description:
      'Compare things: bigger, less expensive, as fast. Then pick the best or the most with the superlative.',
    lessons: [
      {
        type: 'grammar',
        title: 'Comparing and ranking',
        body_markdown: [
          '## Comparative: … que',
          '',
          'Put **plus** (more), **moins** (less) or **aussi** (as) before the adjective and **que** after:',
          '',
          '- Paul est **plus** grand **que** Marie. (taller than)',
          '- Ce livre est **moins** cher **que** l\'autre. (less expensive than)',
          '- Elle est **aussi** intelligente **que** son frère. (as … as)',
          '',
          '## Superlative: le/la/les plus …',
          '',
          'Add the article to say "the most / the least": `C\'est **le plus** cher restaurant.` / `la ville **la plus** belle.`',
          '',
          '## Two irregulars',
          '',
          '`bon` (good) → **meilleur** (better): `Ce vin est **meilleur**.` The adverb `bien` (well) → **mieux** (better): `Tu chantes **mieux** que moi.`',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Useful adjectives',
        body_markdown: 'Comparison words and common adjectives to compare with.',
      },
    ],
    vocab: [
      { lemma_fr: 'plus', translation_en: 'more', pos: 'adverb', ipa: 'ply' },
      { lemma_fr: 'moins', translation_en: 'less', pos: 'adverb', ipa: 'mwɛ̃' },
      { lemma_fr: 'aussi', translation_en: 'as / also', pos: 'adverb', ipa: 'osi' },
      { lemma_fr: 'meilleur', translation_en: 'better (adj.)', pos: 'adjective', ipa: 'mɛjœʁ' },
      { lemma_fr: 'mieux', translation_en: 'better (adv.)', pos: 'adverb', ipa: 'mjø' },
      { lemma_fr: 'cher', translation_en: 'expensive', pos: 'adjective', ipa: 'ʃɛʁ' },
      { lemma_fr: 'rapide', translation_en: 'fast', pos: 'adjective', ipa: 'ʁapid' },
      { lemma_fr: 'facile', translation_en: 'easy', pos: 'adjective', ipa: 'fasil' },
      { lemma_fr: 'difficile', translation_en: 'difficult', pos: 'adjective', ipa: 'difisil' },
      { lemma_fr: 'intéressant', translation_en: 'interesting', pos: 'adjective', ipa: 'ɛ̃teʁesɑ̃' },
      { lemma_fr: 'important', translation_en: 'important', pos: 'adjective', ipa: 'ɛ̃pɔʁtɑ̃' },
      { lemma_fr: 'la ville', translation_en: 'the town / city', pos: 'noun', gender: 'f', ipa: 'la vil' },
    ],
    sentences: [
      { text_fr: 'Paul est plus grand que Marie.', text_en: 'Paul is taller than Marie.' },
      { text_fr: "Ce livre est moins cher que l'autre.", text_en: 'This book is less expensive than the other.' },
      { text_fr: 'Elle est aussi intelligente que son frère.', text_en: 'She is as intelligent as her brother.' },
      { text_fr: "C'est le restaurant le plus cher de la ville.", text_en: "It's the most expensive restaurant in town." },
      { text_fr: "Ce vin est meilleur que l'autre.", text_en: 'This wine is better than the other.' },
      { text_fr: 'Le train est plus rapide que le bus.', text_en: 'The train is faster than the bus.' },
      { text_fr: 'Tu chantes mieux que moi.', text_en: 'You sing better than me.' },
      { text_fr: 'La chimie est plus difficile que la biologie.', text_en: 'Chemistry is more difficult than biology.' },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Paul est ____ grand que Marie. (more)', answer: 'plus', accepted_alternatives: ['plus'] },
      { type: 'cloze', prompt: "Ce vin est ____ que l'autre. (better — from bon)", answer: 'meilleur', accepted_alternatives: ['meilleur'] },
      { type: 'cloze', prompt: "C'est le restaurant le ____ cher de la ville. (most)", answer: 'plus', accepted_alternatives: ['plus'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-travel-transport',
    title_en: 'Travel and Transport',
    title_fr: 'Les voyages et les transports',
    theme: 'travel',
    grammar_focus: 'prepositions of transport and places (en/à, à/au/en + place)',
    description:
      'Get around and go places: by train, on foot, to Paris, to France. Learn the prepositions travel needs.',
    lessons: [
      {
        type: 'grammar',
        title: 'By what, and to where',
        body_markdown: [
          '## Means of transport',
          '',
          'Use **en** for something you get inside, **à** for on foot or on two wheels:',
          '',
          '- **en** voiture, **en** train, **en** avion, **en** bus',
          '- **à** pied (on foot), **à** vélo, **à** moto',
          '',
          '## Going to a place',
          '',
          'To say "to / in" a place:',
          '',
          '- city → **à**: `à Paris`, `à Tokyo`',
          '- feminine country → **en**: `en France`, `en Italie`',
          '- masculine country → **au**: `au Canada`, `au Japon`',
          '- plural country → **aux**: `aux États-Unis`',
          '',
          'Most countries ending in **-e** are feminine (la France, la Chine); a common exception is **le Mexique**.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'On the move',
        body_markdown: 'Transport, tickets and places for travelling.',
      },
    ],
    vocab: [
      { lemma_fr: 'le train', translation_en: 'the train', pos: 'noun', gender: 'm', ipa: 'lə tʁɛ̃' },
      { lemma_fr: "l'avion", translation_en: 'the plane', pos: 'noun', gender: 'm', ipa: 'lavjɔ̃' },
      { lemma_fr: 'la voiture', translation_en: 'the car', pos: 'noun', gender: 'f', ipa: 'la vwatyʁ' },
      { lemma_fr: 'le métro', translation_en: 'the subway', pos: 'noun', gender: 'm', ipa: 'lə metʁo' },
      { lemma_fr: 'le vélo', translation_en: 'the bicycle', pos: 'noun', gender: 'm', ipa: 'lə velo' },
      { lemma_fr: 'à pied', translation_en: 'on foot', pos: 'phrase', ipa: 'a pje' },
      { lemma_fr: 'le billet', translation_en: 'the ticket', pos: 'noun', gender: 'm', ipa: 'lə bijɛ' },
      { lemma_fr: 'la gare', translation_en: 'the (train) station', pos: 'noun', gender: 'f', ipa: 'la ɡaʁ' },
      { lemma_fr: "l'aéroport", translation_en: 'the airport', pos: 'noun', gender: 'm', ipa: 'laeʁɔpɔʁ' },
      { lemma_fr: 'voyager', translation_en: 'to travel', pos: 'verb', ipa: 'vwajaʒe' },
      { lemma_fr: 'le voyage', translation_en: 'the trip', pos: 'noun', gender: 'm', ipa: 'lə vwajaʒ' },
      { lemma_fr: 'les vacances', translation_en: 'the holidays', pos: 'noun', gender: 'f', ipa: 'le vakɑ̃s' },
    ],
    sentences: [
      { text_fr: 'Je vais au travail en métro.', text_en: 'I go to work by subway.' },
      { text_fr: 'Nous voyageons en train.', text_en: 'We travel by train.' },
      { text_fr: 'Elle va à Paris en avion.', text_en: "She's going to Paris by plane." },
      { text_fr: "J'ai acheté un billet à la gare.", text_en: 'I bought a ticket at the station.' },
      { text_fr: "Ils vont à l'école à pied.", text_en: 'They walk to school.' },
      { text_fr: 'Tu vas en France cet été ?', text_en: 'Are you going to France this summer?' },
      { text_fr: 'Il habite au Canada.', text_en: 'He lives in Canada.' },
      { text_fr: "L'avion part de l'aéroport à midi.", text_en: 'The plane leaves the airport at noon.' },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Je vais au travail ____ métro. (by)', answer: 'en', accepted_alternatives: ['en'] },
      { type: 'cloze', prompt: "Ils vont à l'école ____ pied. (on foot)", answer: 'à', accepted_alternatives: ['à'] },
      { type: 'cloze', prompt: 'Il habite ____ Canada. (masculine country)', answer: 'au', accepted_alternatives: ['au'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-restaurant',
    title_en: 'At the Restaurant',
    title_fr: 'Au restaurant',
    theme: 'food',
    grammar_focus: 'the partitive article (du, de la, des)',
    description:
      'Order a meal and use the partitive article — "some" bread, "some" water — the way French marks an unspecified quantity.',
    lessons: [
      {
        type: 'grammar',
        title: 'Some of something: the partitive',
        body_markdown: [
          '## du, de la, de l\', des',
          '',
          'For an **unspecified amount** ("some / any"), French uses the partitive article:',
          '',
          '- **du** + masculine: `du pain`, `du café`',
          '- **de la** + feminine: `de la soupe`, `de la glace`',
          '- **de l\'** + vowel: `de l\'eau`, `de l\'huile`',
          '- **des** + plural: `des frites`, `des légumes`',
          '',
          '## After a negative → de',
          '',
          'All of these become **de / d\'** after a negative: `Je prends du vin.` → `Je ne prends **pas de** vin.`',
          '',
          '## Ordering politely',
          '',
          'Use `je voudrais` (I would like) and `je vais prendre` (I\'ll have): `Je voudrais **de la** soupe et **du** pain.`',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'At the table',
        body_markdown: 'Words for ordering and eating out.',
      },
    ],
    vocab: [
      { lemma_fr: 'le menu', translation_en: 'the set menu', pos: 'noun', gender: 'm', ipa: 'lə məny' },
      { lemma_fr: 'la carte', translation_en: 'the menu (à la carte)', pos: 'noun', gender: 'f', ipa: 'la kaʁt' },
      { lemma_fr: "l'entrée", translation_en: 'the starter', pos: 'noun', gender: 'f', ipa: 'lɑ̃tʁe' },
      { lemma_fr: 'le plat', translation_en: 'the (main) dish', pos: 'noun', gender: 'm', ipa: 'lə pla' },
      { lemma_fr: 'le dessert', translation_en: 'the dessert', pos: 'noun', gender: 'm', ipa: 'lə desɛʁ' },
      { lemma_fr: 'la boisson', translation_en: 'the drink', pos: 'noun', gender: 'f', ipa: 'la bwasɔ̃' },
      { lemma_fr: "l'addition", translation_en: 'the bill / check', pos: 'noun', gender: 'f', ipa: 'ladisjɔ̃' },
      { lemma_fr: 'commander', translation_en: 'to order', pos: 'verb', ipa: 'kɔmɑ̃de' },
      { lemma_fr: 'le serveur', translation_en: 'the waiter', pos: 'noun', gender: 'm', ipa: 'lə sɛʁvœʁ' },
      { lemma_fr: "l'eau", translation_en: 'the water', pos: 'noun', gender: 'f', ipa: 'lo' },
      { lemma_fr: 'le pain', translation_en: 'the bread', pos: 'noun', gender: 'm', ipa: 'lə pɛ̃' },
      { lemma_fr: 'le vin', translation_en: 'the wine', pos: 'noun', gender: 'm', ipa: 'lə vɛ̃' },
    ],
    sentences: [
      { text_fr: "Je voudrais commander, s'il vous plaît.", text_en: 'I would like to order, please.' },
      { text_fr: "Vous prenez de l'eau ou du vin ?", text_en: 'Will you have water or wine?' },
      { text_fr: 'Elle mange de la soupe.', text_en: "She's eating soup." },
      { text_fr: 'Je prends du pain avec le fromage.', text_en: "I'll have bread with the cheese." },
      { text_fr: 'Comme dessert, je voudrais de la glace.', text_en: "For dessert, I'd like ice cream." },
      { text_fr: "L'addition, s'il vous plaît !", text_en: 'The bill, please!' },
      { text_fr: 'Nous ne prenons pas de dessert.', text_en: "We're not having dessert." },
      { text_fr: 'Le serveur apporte la carte.', text_en: 'The waiter brings the menu.' },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Elle mange ____ soupe. (some — feminine)', answer: 'de la', accepted_alternatives: ['de la'] },
      { type: 'cloze', prompt: 'Je prends ____ pain. (some — masculine)', answer: 'du', accepted_alternatives: ['du'] },
      { type: 'cloze', prompt: 'Nous ne prenons pas ____ dessert. (after a negative)', answer: 'de', accepted_alternatives: ['de'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-quantities',
    title_en: 'Shopping and Quantities',
    title_fr: 'Les courses et les quantités',
    theme: 'shopping',
    grammar_focus: 'expressions of quantity + de',
    description:
      'Go shopping and measure things out: a kilo of, a lot of, too much. After a quantity word, French uses a plain de.',
    lessons: [
      {
        type: 'grammar',
        title: 'Quantity + de',
        body_markdown: [
          '## The rule: quantity → de',
          '',
          'After any expression of quantity, use **de / d\'** — never du/de la/des:',
          '',
          '- **beaucoup de** pommes — a lot of apples',
          '- **un peu de** lait — a little milk',
          '- **trop de** sucre — too much sugar',
          '- **assez de** temps — enough time',
          '- **un kilo de** tomates, **une bouteille d\'**eau, **un morceau de** gâteau',
          '',
          '## Asking prices',
          '',
          'Ask with **combien**: `**Combien** coûte ce melon ?` / `Ça fait **combien** ?` — the answer often ends `… euros`.',
          '',
          'Note: `de` stays invariable here, even before a plural: `beaucoup **de** livres` (not "des").',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Shopping words',
        body_markdown: 'Places, quantities and money for doing the shopping.',
      },
    ],
    vocab: [
      { lemma_fr: 'le marché', translation_en: 'the market', pos: 'noun', gender: 'm', ipa: 'lə maʁʃe' },
      { lemma_fr: 'le magasin', translation_en: 'the shop', pos: 'noun', gender: 'm', ipa: 'lə maɡazɛ̃' },
      { lemma_fr: 'acheter', translation_en: 'to buy', pos: 'verb', ipa: 'aʃte' },
      { lemma_fr: 'le prix', translation_en: 'the price', pos: 'noun', gender: 'm', ipa: 'lə pʁi' },
      { lemma_fr: "l'argent", translation_en: 'the money', pos: 'noun', gender: 'm', ipa: 'laʁʒɑ̃' },
      { lemma_fr: 'un kilo', translation_en: 'a kilo', pos: 'noun', gender: 'm', ipa: 'œ̃ kilo' },
      { lemma_fr: 'une bouteille', translation_en: 'a bottle', pos: 'noun', gender: 'f', ipa: 'yn butɛj' },
      { lemma_fr: 'un morceau', translation_en: 'a piece', pos: 'noun', gender: 'm', ipa: 'œ̃ mɔʁso' },
      { lemma_fr: 'beaucoup', translation_en: 'a lot / many', pos: 'adverb', ipa: 'boku' },
      { lemma_fr: 'un peu', translation_en: 'a little', pos: 'adverb', ipa: 'œ̃ pø' },
      { lemma_fr: 'assez', translation_en: 'enough', pos: 'adverb', ipa: 'ase' },
      { lemma_fr: 'trop', translation_en: 'too much / too many', pos: 'adverb', ipa: 'tʁo' },
    ],
    sentences: [
      { text_fr: 'Je voudrais un kilo de pommes.', text_en: "I'd like a kilo of apples." },
      { text_fr: 'Il y a beaucoup de monde au marché.', text_en: 'There are a lot of people at the market.' },
      { text_fr: "Elle achète une bouteille d'eau.", text_en: "She's buying a bottle of water." },
      { text_fr: "C'est trop cher pour moi.", text_en: "It's too expensive for me." },
      { text_fr: 'Nous avons assez de pain.', text_en: 'We have enough bread.' },
      { text_fr: 'Je prends un peu de fromage.', text_en: "I'll take a little cheese." },
      { text_fr: 'Combien coûte ce livre ?', text_en: 'How much does this book cost?' },
      { text_fr: 'Il achète un morceau de gâteau.', text_en: "He's buying a piece of cake." },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Je voudrais un kilo ____ pommes. (of)', answer: 'de', accepted_alternatives: ['de'] },
      { type: 'cloze', prompt: "C'est ____ cher pour moi. (too much)", answer: 'trop', accepted_alternatives: ['trop'] },
      { type: 'cloze', prompt: 'Nous avons ____ de pain. (enough)', answer: 'assez', accepted_alternatives: ['assez'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-health',
    title_en: 'Health and the Body',
    title_fr: 'La santé et le corps',
    theme: 'health',
    grammar_focus: 'avoir mal à (au / à la / aux) and talking about illness',
    description:
      "Say what hurts and how you feel. Learn avoir mal à and the vocabulary of a visit to the doctor.",
    lessons: [
      {
        type: 'grammar',
        title: 'Saying what hurts',
        body_markdown: [
          '## avoir mal à',
          '',
          'To say a body part hurts, use **avoir mal à** + the part. The **à** merges with the article:',
          '',
          '- à + le → **au**: `J\'ai mal **au** dos.` (my back hurts)',
          '- à + la → **à la**: `J\'ai mal **à la** tête.` (headache)',
          '- à + l\' → **à l\'**: `J\'ai mal **à l\'**oreille.`',
          '- à + les → **aux**: `J\'ai mal **aux** dents.` (toothache)',
          '',
          '## Other useful expressions',
          '',
          '- `être malade` — to be sick; `avoir de la fièvre` — to have a fever',
          '- `se sentir bien / mal` — to feel well / unwell',
          '- `Qu\'est-ce qui ne va pas ?` — What\'s wrong?',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Body and illness',
        body_markdown: 'Parts of the body and words for being unwell.',
      },
    ],
    vocab: [
      { lemma_fr: 'la santé', translation_en: 'health', pos: 'noun', gender: 'f', ipa: 'la sɑ̃te' },
      { lemma_fr: 'le médecin', translation_en: 'the doctor', pos: 'noun', gender: 'm', ipa: 'lə medsɛ̃' },
      { lemma_fr: 'malade', translation_en: 'sick', pos: 'adjective', ipa: 'malad' },
      { lemma_fr: 'la tête', translation_en: 'the head', pos: 'noun', gender: 'f', ipa: 'la tɛt' },
      { lemma_fr: 'le ventre', translation_en: 'the stomach / belly', pos: 'noun', gender: 'm', ipa: 'lə vɑ̃tʁ' },
      { lemma_fr: 'la gorge', translation_en: 'the throat', pos: 'noun', gender: 'f', ipa: 'la ɡɔʁʒ' },
      { lemma_fr: 'le dos', translation_en: 'the back', pos: 'noun', gender: 'm', ipa: 'lə do' },
      { lemma_fr: 'la fièvre', translation_en: 'the fever', pos: 'noun', gender: 'f', ipa: 'la fjɛvʁ' },
      { lemma_fr: 'le rhume', translation_en: 'the cold', pos: 'noun', gender: 'm', ipa: 'lə ʁym' },
      { lemma_fr: 'la pharmacie', translation_en: 'the pharmacy', pos: 'noun', gender: 'f', ipa: 'la faʁmasi' },
      { lemma_fr: 'le médicament', translation_en: 'the medicine', pos: 'noun', gender: 'm', ipa: 'lə medikamɑ̃' },
      { lemma_fr: 'se sentir', translation_en: 'to feel', pos: 'verb', ipa: 'sə sɑ̃tiʁ' },
    ],
    sentences: [
      { text_fr: "J'ai mal à la tête.", text_en: 'I have a headache.' },
      { text_fr: 'Il a mal au ventre.', text_en: 'He has a stomachache.' },
      { text_fr: 'Elle a de la fièvre depuis hier.', text_en: "She's had a fever since yesterday." },
      { text_fr: 'Je ne me sens pas bien.', text_en: "I don't feel well." },
      { text_fr: 'Tu devrais aller chez le médecin.', text_en: 'You should go to the doctor.' },
      { text_fr: "J'ai attrapé un rhume.", text_en: 'I caught a cold.' },
      { text_fr: 'Il a mal aux dents.', text_en: 'He has a toothache.' },
      { text_fr: 'Prends ce médicament deux fois par jour.', text_en: 'Take this medicine twice a day.' },
    ],
    exercises: [
      { type: 'cloze', prompt: "J'ai mal ____ tête. (à + la)", answer: 'à la', accepted_alternatives: ['à la'] },
      { type: 'cloze', prompt: 'Il a mal ____ ventre. (à + le)', answer: 'au', accepted_alternatives: ['au'] },
      { type: 'cloze', prompt: 'Il a mal ____ dents. (à + les)', answer: 'aux', accepted_alternatives: ['aux'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-y-en',
    title_en: 'The Pronouns y and en',
    title_fr: 'Les pronoms y et en',
    theme: 'grammar',
    grammar_focus: 'the pronouns y (place) and en (quantity)',
    description:
      'Two short but essential pronouns: y replaces a place or à + thing, and en replaces de + thing or a quantity.',
    lessons: [
      {
        type: 'grammar',
        title: 'y and en',
        body_markdown: [
          '## y — there / to it',
          '',
          '**y** replaces a **place** or **à + a thing**. It sits before the verb:',
          '',
          '- Tu vas à Paris ? — Oui, j\'**y** vais. (I\'m going there.)',
          '- Elle habite à Lyon ? — Elle **y** habite.',
          '- Tu penses à ton examen ? — J\'**y** pense.',
          '',
          '## en — some / of it',
          '',
          '**en** replaces **de + a thing**, or a noun after a quantity or number:',
          '',
          '- Tu veux du café ? — Oui, j\'**en** veux. (I want some.)',
          '- Combien de livres as-tu ? — J\'**en** ai trois. (I have three of them.)',
          '- Vous avez des enfants ? — J\'**en** ai deux.',
          '',
          'With a number or quantity, **keep it at the end**: `J\'en ai **beaucoup**.`',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Places and amounts',
        body_markdown: 'Words about location and about coming and going.',
      },
    ],
    vocab: [
      { lemma_fr: 'le quartier', translation_en: 'the neighbourhood', pos: 'noun', gender: 'm', ipa: 'lə kaʁtje' },
      { lemma_fr: "l'endroit", translation_en: 'the place', pos: 'noun', gender: 'm', ipa: 'lɑ̃dʁwa' },
      { lemma_fr: 'le centre-ville', translation_en: 'the city centre', pos: 'noun', gender: 'm', ipa: 'lə sɑ̃tʁ vil' },
      { lemma_fr: 'la banque', translation_en: 'the bank', pos: 'noun', gender: 'f', ipa: 'la bɑ̃k' },
      { lemma_fr: 'la poste', translation_en: 'the post office', pos: 'noun', gender: 'f', ipa: 'la pɔst' },
      { lemma_fr: 'le parc', translation_en: 'the park', pos: 'noun', gender: 'm', ipa: 'lə paʁk' },
      { lemma_fr: 'se trouver', translation_en: 'to be located', pos: 'verb', ipa: 'sə tʁuve' },
      { lemma_fr: 'près', translation_en: 'near', pos: 'adverb', ipa: 'pʁɛ' },
      { lemma_fr: 'loin', translation_en: 'far', pos: 'adverb', ipa: 'lwɛ̃' },
      { lemma_fr: 'penser', translation_en: 'to think', pos: 'verb', ipa: 'pɑ̃se' },
      { lemma_fr: 'revenir', translation_en: 'to come back', pos: 'verb', ipa: 'ʁəvəniʁ' },
      { lemma_fr: 'quelques', translation_en: 'a few', pos: 'adjective', ipa: 'kɛlkə' },
    ],
    sentences: [
      { text_fr: "Tu vas à Paris ? Oui, j'y vais demain.", text_en: "Are you going to Paris? Yes, I'm going there tomorrow." },
      { text_fr: 'Elle habite à Lyon ? Oui, elle y habite.', text_en: 'Does she live in Lyon? Yes, she lives there.' },
      { text_fr: "Tu veux du café ? Oui, j'en veux.", text_en: 'Do you want coffee? Yes, I want some.' },
      { text_fr: "Combien de livres as-tu ? J'en ai trois.", text_en: 'How many books do you have? I have three.' },
      { text_fr: 'Il y a un parc dans le quartier.', text_en: "There's a park in the neighbourhood." },
      { text_fr: "Vous avez des enfants ? Oui, j'en ai deux.", text_en: 'Do you have children? Yes, I have two.' },
      { text_fr: "Le musée ? J'y suis allé hier.", text_en: 'The museum? I went there yesterday.' },
      { text_fr: 'La banque se trouve près de la poste.', text_en: 'The bank is located near the post office.' },
    ],
    exercises: [
      { type: 'cloze', prompt: "Tu vas à Paris ? Oui, j'____ vais. (there)", answer: 'y', accepted_alternatives: ['y'] },
      { type: 'cloze', prompt: "Tu veux du café ? Oui, j'____ veux. (some)", answer: 'en', accepted_alternatives: ['en'] },
      { type: 'cloze', prompt: "Combien de livres ? J'____ ai trois. (of them)", answer: 'en', accepted_alternatives: ['en'] },
    ],
  },

  {
    level: 'A2',
    slug: 'a2-connectors',
    title_en: 'Linking Words',
    title_fr: 'Les connecteurs logiques',
    theme: 'grammar',
    grammar_focus: 'connectors: parce que, donc, mais, alors, pendant que',
    description:
      'Join your ideas into real sentences. Explain, contrast and sequence with because, so, but, then and while.',
    lessons: [
      {
        type: 'grammar',
        title: 'Connecting ideas',
        body_markdown: [
          '## Cause and result',
          '',
          '- **parce que** — because (gives a reason): `Je reste parce qu\'il pleut.`',
          '- **car** — for / because (a bit more formal): `Je n\'y vais pas, car je suis fatigué.`',
          '- **donc** — so / therefore (a result): `Il est malade, donc il reste au lit.`',
          '- **alors** — so / then (a consequence in speech): `Il pleut, alors je prends un parapluie.`',
          '',
          '## Contrast and sequence',
          '',
          '- **mais** — but: `Je veux venir, mais je n\'ai pas le temps.`',
          '- **pourtant** — yet / however: `C\'est cher, pourtant je vais l\'acheter.`',
          '- **pendant que** — while (same time): `Elle lit pendant que je cuisine.`',
          '- **d\'abord … puis … enfin** — first … then … finally.',
          '',
          '> `parce que` answers *why?*; `donc`/`alors` state the *result*. Don\'t start an answer to "pourquoi ?" with donc.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Connectors',
        body_markdown: 'The little words that hold sentences together.',
      },
    ],
    vocab: [
      { lemma_fr: 'parce que', translation_en: 'because', pos: 'conjunction', ipa: 'paʁs kə' },
      { lemma_fr: 'car', translation_en: 'because / for', pos: 'conjunction', ipa: 'kaʁ' },
      { lemma_fr: 'donc', translation_en: 'so / therefore', pos: 'conjunction', ipa: 'dɔ̃k' },
      { lemma_fr: 'alors', translation_en: 'so / then', pos: 'adverb', ipa: 'alɔʁ' },
      { lemma_fr: 'mais', translation_en: 'but', pos: 'conjunction', ipa: 'mɛ' },
      { lemma_fr: 'pourtant', translation_en: 'yet / however', pos: 'adverb', ipa: 'puʁtɑ̃' },
      { lemma_fr: 'pendant que', translation_en: 'while', pos: 'conjunction', ipa: 'pɑ̃dɑ̃ kə' },
      { lemma_fr: 'puis', translation_en: 'then / next', pos: 'adverb', ipa: 'pɥi' },
      { lemma_fr: 'enfin', translation_en: 'finally', pos: 'adverb', ipa: 'ɑ̃fɛ̃' },
      { lemma_fr: 'cependant', translation_en: 'however', pos: 'adverb', ipa: 'səpɑ̃dɑ̃' },
      { lemma_fr: 'pourquoi', translation_en: 'why', pos: 'adverb', ipa: 'puʁkwa' },
      { lemma_fr: 'ainsi', translation_en: 'thus / in this way', pos: 'adverb', ipa: 'ɛ̃si' },
    ],
    sentences: [
      { text_fr: "Je reste à la maison parce qu'il pleut.", text_en: "I'm staying home because it's raining." },
      { text_fr: 'Il est malade, donc il ne vient pas.', text_en: "He's sick, so he's not coming." },
      { text_fr: "Je veux venir, mais je n'ai pas le temps.", text_en: "I want to come, but I don't have time." },
      { text_fr: 'Il pleut, alors je prends un parapluie.', text_en: "It's raining, so I'm taking an umbrella." },
      { text_fr: 'Elle lit pendant que je cuisine.', text_en: 'She reads while I cook.' },
      { text_fr: "C'est cher, pourtant je vais l'acheter.", text_en: "It's expensive, yet I'm going to buy it." },
      { text_fr: "D'abord on mange, puis on sort.", text_en: 'First we eat, then we go out.' },
      { text_fr: 'Je suis fatigué, car je me suis couché tard.', text_en: 'I am tired, because I went to bed late.' },
    ],
    exercises: [
      { type: 'cloze', prompt: 'Il est malade, ____ il ne vient pas. (so)', answer: 'donc', accepted_alternatives: ['donc'] },
      { type: 'cloze', prompt: "Je veux venir, ____ je n'ai pas le temps. (but)", answer: 'mais', accepted_alternatives: ['mais'] },
      { type: 'cloze', prompt: 'Il pleut, ____ je prends un parapluie. (so / then)', answer: 'alors', accepted_alternatives: ['alors'] },
    ],
  },
];
