/*
 * Content-sync — upgrade a user's database to newer bundled content WITHOUT
 * wiping their progress.
 *
 * Why this exists: content (units/lessons/vocab/authored-sentences/exercises) is
 * regenerated by content/build.ts on every release, while progress (cards' FSRS
 * state, review_logs, unit unlocks, streak/XP) is user-owned and must survive.
 * Because content ids are now *stable* (deterministic hashes of a natural key,
 * see build.ts), a card that points at vocab #<hash> keeps pointing at the right
 * row across rebuilds — so the sync is a plain, idempotent upsert + prune with no
 * id remapping and no transaction required. If it's interrupted, the version bump
 * (done last) simply hasn't happened, and the next launch re-runs and converges.
 *
 * This module is deliberately free of any Tauri import so it can be unit-tested
 * against node:sqlite (see content-sync.test.ts). The plugin glue that loads the
 * seed sidecar handle lives in client.ts.
 *
 * Scope note: the ~30k Tatoeba *pool* sentences (unit_id IS NULL) are static and
 * large, so they are intentionally NOT synced — they stay as first-seeded. Only
 * unit-linked content is reconciled.
 */

/** Minimal async DB surface satisfied by @tauri-apps/plugin-sql's `Database`. */
export interface SqlExecutor {
  select<T>(query: string, values?: unknown[]): Promise<T>;
  execute(query: string, values?: unknown[]): Promise<unknown>;
}

// Full column lists (order matches the schema); used to build upserts by id.
const UNIT_COLS = [
  'id', 'level', 'order_index', 'slug', 'title_en', 'title_fr', 'theme',
  'grammar_focus', 'description',
] as const;
const LESSON_COLS = ['id', 'unit_id', 'order_index', 'type', 'title', 'body_markdown'] as const;
const VOCAB_COLS = [
  'id', 'unit_id', 'lemma_fr', 'translation_en', 'pos', 'gender', 'ipa',
  'example_sentence_id', 'frequency_rank', 'audio_path',
] as const;
const SENTENCE_COLS = [
  'id', 'text_fr', 'text_en', 'tatoeba_id', 'difficulty_score', 'word_count',
  'unit_id', 'audio_path', 'tags',
] as const;
// Exercises carry no cross-boundary references, so they're replaced wholesale and
// re-inserted with fresh autoincrement ids (id omitted).
const EXERCISE_COLS = [
  'unit_id', 'sentence_id', 'vocab_id', 'type', 'direction', 'prompt', 'answer',
  'accepted_alternatives', 'distractors', 'audio_path',
] as const;

type Row = Record<string, unknown>;

export interface SyncResult {
  from: number;
  to: number;
  changed: boolean;
}

async function contentVersion(db: SqlExecutor): Promise<number> {
  const rows = await db.select<{ value: string }[]>(
    "SELECT value FROM settings WHERE key = 'content_version'",
  );
  return rows[0] ? Number(rows[0].value) : 0;
}

function* chunk<T>(items: readonly T[], size: number): Generator<T[]> {
  for (let i = 0; i < items.length; i += size) yield items.slice(i, i + size);
}

/** Positional `$n` placeholder tuples for `count` rows of `width` columns. */
function placeholders(count: number, width: number): string {
  let n = 0;
  return Array.from({ length: count }, () => `(${Array.from({ length: width }, () => `$${++n}`).join(', ')})`).join(', ');
}

/** Upsert rows into `table` keyed on the stable `id` primary key. */
async function upsertById(
  db: SqlExecutor,
  table: string,
  cols: readonly string[],
  rows: readonly Row[],
): Promise<void> {
  if (rows.length === 0) return;
  const setClause = cols.filter((c) => c !== 'id').map((c) => `${c} = excluded.${c}`).join(', ');
  const perChunk = Math.max(1, Math.floor(900 / cols.length));
  for (const part of chunk(rows, perChunk)) {
    const sql =
      `INSERT INTO ${table} (${cols.join(', ')}) VALUES ${placeholders(part.length, cols.length)} ` +
      `ON CONFLICT(id) DO UPDATE SET ${setClause}`;
    await db.execute(sql, part.flatMap((r) => cols.map((c) => r[c] ?? null)));
  }
}

/** Insert rows (no conflict handling); used for the wholesale exercise refresh. */
async function insertAll(
  db: SqlExecutor,
  table: string,
  cols: readonly string[],
  rows: readonly Row[],
): Promise<void> {
  if (rows.length === 0) return;
  const perChunk = Math.max(1, Math.floor(900 / cols.length));
  for (const part of chunk(rows, perChunk)) {
    const sql = `INSERT INTO ${table} (${cols.join(', ')}) VALUES ${placeholders(part.length, cols.length)}`;
    await db.execute(sql, part.flatMap((r) => cols.map((c) => r[c] ?? null)));
  }
}

/** Delete rows of `table` where `col` is in `ids` (chunked to stay under the bind limit). */
async function deleteByIds(
  db: SqlExecutor,
  table: string,
  col: string,
  ids: readonly number[],
): Promise<void> {
  for (const part of chunk(ids, 500)) {
    const sql = `DELETE FROM ${table} WHERE ${col} IN (${part.map((_, i) => `$${i + 1}`).join(', ')})`;
    await db.execute(sql, part.slice());
  }
}

async function idSet(db: SqlExecutor, sql: string): Promise<Set<number>> {
  const rows = await db.select<{ id: number }[]>(sql);
  return new Set(rows.map((r) => Number(r.id)));
}

function missingFrom(have: Iterable<number>, keep: Set<number>): number[] {
  const out: number[] = [];
  for (const id of have) if (!keep.has(id)) out.push(id);
  return out;
}

/**
 * Bring `user`'s content up to `seed`'s, preserving progress. Idempotent and
 * safe to re-run. Returns what changed. A no-op when the user is already current.
 */
export async function syncContent(user: SqlExecutor, seed: SqlExecutor): Promise<SyncResult> {
  const to = await contentVersion(seed);
  const from = await contentVersion(user);
  if (to <= from) return { from, to, changed: false };

  // Read the seed's content up front.
  const units = await seed.select<Row[]>('SELECT * FROM units');
  const lessons = await seed.select<Row[]>('SELECT * FROM lessons');
  const vocab = await seed.select<Row[]>('SELECT * FROM vocab');
  const sentences = await seed.select<Row[]>('SELECT * FROM sentences WHERE unit_id IS NOT NULL');
  const exercises = await seed.select<Row[]>('SELECT * FROM exercises');

  // 1) Clear exercises first: they hold FKs to content, so emptying the table
  //    lets us prune stale content below without FK violations. (Re-filled in 5.)
  await user.execute('DELETE FROM exercises');

  // 2) Prune content the new release no longer has, children before parents.
  //    "Stale" = a row in the user DB whose stable id isn't in the seed. Doing
  //    this BEFORE the upsert matters: on the one-time id migration the seed's
  //    row shares a UNIQUE slug with the old row, so the old one must go first.
  //    Pool sentences (unit_id IS NULL) are excluded — they aren't synced.
  const keepUnits = new Set(units.map((u) => Number(u.id)));
  const keepLessons = new Set(lessons.map((l) => Number(l.id)));
  const keepVocab = new Set(vocab.map((v) => Number(v.id)));
  const keepSentences = new Set(sentences.map((s) => Number(s.id)));

  await deleteByIds(user, 'vocab', 'id',
    missingFrom(await idSet(user, 'SELECT id FROM vocab'), keepVocab));
  await deleteByIds(user, 'sentences', 'id',
    missingFrom(await idSet(user, 'SELECT id FROM sentences WHERE unit_id IS NOT NULL'), keepSentences));
  await deleteByIds(user, 'lessons', 'id',
    missingFrom(await idSet(user, 'SELECT id FROM lessons'), keepLessons));
  const removedUnits = missingFrom(await idSet(user, 'SELECT id FROM units'), keepUnits);
  await deleteByIds(user, 'unit_progress', 'unit_id', removedUnits);
  await deleteByIds(user, 'units', 'id', removedUnits);

  // 3) Drop cards (and their logs) whose item no longer exists after the prune,
  //    before any new cards are added.
  const orphanCardIds =
    'SELECT c.id FROM cards c WHERE ' +
    "(c.item_type = 'vocab' AND NOT EXISTS (SELECT 1 FROM vocab v WHERE v.id = c.item_id)) OR " +
    "(c.item_type = 'sentence' AND NOT EXISTS (SELECT 1 FROM sentences s WHERE s.id = c.item_id)) OR " +
    "(c.item_type = 'grammar' AND NOT EXISTS (SELECT 1 FROM lessons l WHERE l.id = c.item_id))";
  // Logs first (they reference cards.id), then the orphan cards themselves.
  await user.execute(`DELETE FROM review_logs WHERE card_id IN (${orphanCardIds})`);
  await user.execute(`DELETE FROM cards WHERE id IN (${orphanCardIds})`);

  // 4) Upsert current content by stable id (adds new, updates edited in place).
  await upsertById(user, 'units', UNIT_COLS, units);
  await upsertById(user, 'lessons', LESSON_COLS, lessons);
  await upsertById(user, 'vocab', VOCAB_COLS, vocab);
  await upsertById(user, 'sentences', SENTENCE_COLS, sentences);

  // 5) Re-fill exercises from the seed (fresh autoincrement ids; nothing refers
  //    to an exercise id across the boundary).
  await insertAll(user, 'exercises', EXERCISE_COLS, exercises);

  // 6) Add cards for new content. UNIQUE(item_type,item_id) means a card the user
  //    has already studied is left as-is, keeping its FSRS state.
  const seedCards = await seed.select<{ item_type: string; item_id: number }[]>(
    'SELECT item_type, item_id FROM cards',
  );
  for (const part of chunk(seedCards, 300)) {
    let n = 0;
    const tuples = part.map(() => `($${++n}, $${++n}, 'new')`).join(', ');
    await user.execute(
      `INSERT OR IGNORE INTO cards (item_type, item_id, state) VALUES ${tuples}`,
      part.flatMap((c) => [c.item_type, c.item_id]),
    );
  }

  // 7) Ensure a unit_progress row per unit. New units get the seed's default
  //    status; the user's earned status on existing units is kept (OR IGNORE).
  const seedProgress = await seed.select<Row[]>('SELECT * FROM unit_progress');
  for (const part of chunk(seedProgress, 200)) {
    let n = 0;
    const tuples = part.map(() => `($${++n}, $${++n}, $${++n}, $${++n})`).join(', ');
    await user.execute(
      `INSERT OR IGNORE INTO unit_progress (unit_id, status, lessons_done, completed_at) VALUES ${tuples}`,
      part.flatMap((p) => [p['unit_id'], p['status'], p['lessons_done'] ?? '[]', p['completed_at'] ?? null]),
    );
  }

  // 8) Record the new version last, so an interrupted run re-runs next launch.
  await user.execute(
    `INSERT INTO settings (key, value) VALUES ('content_version', $1)
     ON CONFLICT(key) DO UPDATE SET value = excluded.value`,
    [String(to)],
  );

  return { from, to, changed: true };
}
